### ISSUE TITLE
Suggestions for improving output of stylish formatter

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#101]
**Describe the bug**
(1) Consistent spacing so that there is no "shifted column" effect
(2) Output should expand across all of terminal width (seems like a regression @nbrahms)?
(3) The blue text is unreadable on my terminal, does anyone else have this problem (@dlukeomalley ?)

**Expected result**

```
680:93  error   invalid escape sequence '\.'                                                                         r2c.flake8     W605
680:105 error   invalid escape sequence '\.'                                                                         r2c.flake8     W605
```

**Actual result**
```
680:93 error   invalid escape sequence '\.'                                                                         r2c.flake8     W605
680:105 error   invalid escape sequence '\.'                                                                         r2c.flake8     W605
```
**Additional context**
bento/0.2.0b1-isaac

**Comment by nbrahms** [comment]
Hi @ievans ,

Thanks for the feedback!

@dlukeomalley Can we split this into multiple issues?

Quick response here:
1. Yes, this should be improved. We'll work on that.
2. We intentionally do not expand the "message" column beyond the length of the longest message, as a large gutter of whitespace makes it difficult to correlate finding to tool and rule.
3. Are you using a specific terminal and theme? I've validated readability so far using MacOS iterm2 "light" and "solarized dark" themes.

**Comment by ievans** [comment]
@nbrahms for #2 what I'm seeing is that it truncates even when I have more space:

![image](https://user-images.githubusercontent.com/409041/66862919-c72ee800-ef46-11e9-916c-fed4ce5c6936.png)

On #3, this is iterm2 with "dark background" color preset. Separately though, I'd make an argument against blue that I haven't seen any other CLI products use it.

**Comment by dlukeomalley** [comment]
From a user today:

> -- default output formatter is not very transactable as plaintext

**Comment by ievans** [comment]
In particular, the character trimming into ... is very annoying, as I can't read the full output of some check text:

` 12:13 error   Loop control variable 'i' not used within the loop body. If this is intended, start the name with... r2c.flake8     B007`

**Comment by dlukeomalley** [comment]
@ievans We're tracking improvements to this in soon-to-be-released 0.3.0.

**Comment by dlukeomalley** [comment]
@ievans I'd like to close this issue in favor of:

1. https://github.com/returntocorp/bento/issues/156
2. https://github.com/returntocorp/bento/issues/155

Am I missing any follow on issues from your experience?

**Comment by ievans** [comment]
@dlukeomalley looks good, thank you!
