### ISSUE TITLE
Make `bento disable` case insensitive

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#103]
Nice to have: make `bento enable/disable` case insensitive.

```bash
$ bento disable r2c.flake8 f401
✔ 'f401' disabled for 'r2c.flake8'

$ bento check
Running Bento checks...
  r2c.bandit: |███████████████| 00:01, 🍱
  r2c.flake8: |███████████████| 00:01, 🍱

app/models.py
  5:1  error   'django.db.models' imported but unused               r2c.flake8     F401

app/views.py
  7:1  error   'django.template.RequestContext' imported but unused r2c.flake8     F401

⚠ 2 findings in 1.71 s

To suppress all findings run `bento archive`.

$ bento disable r2c.flake8 F401
✔ 'F401' disabled for 'r2c.flake8'
```

**Comment by ievans** [comment]
what if we unified the tool check namespace:

r2c.flake8     F401 -> r2c.flake8.F401

then you could just copy/paste the id of the thing you want to disable

**Comment by nbrahms** [comment]
@ievans FWIW, you can already copy and paste, as shells don't care about intervening spaces. I'm not sure how to make this discoverable to users, though.

**Comment by ievans** [comment]
@nbrahms TIL!

**Comment by dlukeomalley** [comment]
For the time being we've decided to pass on this feature. Instead we've discussed and are going to alias checks from tools like Bandit and Flake8 to be both human readable, and likely also lower case.

Auto-complete also greatly assists with typing this correctly.
