### ISSUE TITLE
Infinite loop if commit hooks installed twice

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#111]
**Describe the bug**
I ran `git commit -m "message"` when no files are staged. Waited for while in a seemingly infinite loop.

This appears to have happened when commit hooks are installed twice, previously. Removing commit hooks from `.git/hooks` solves the issue.

**Expected result**
Bento wouldn't find anything.

**Actual result**
I waited a long time and nothing printed, has to ctrl+c twice to get out.

**Additional context**
Committing with `bento/0.1.1b4` on `minimal-flask-react`

**Comment by arashd** [comment]
Issue was caused because of installing commit hooks twice. Not sure how I got into this state if bento checks for previously installed hooks. I'll change the name/description of the issue because of this.

**Comment by nbrahms** [comment]
Hi @arashd ... I think we should close this, as this was due to using an outdated version of the tool.

**Comment by arashd** [comment]
Hmm, ok! I’ll assume I got into this broken state when I had an old version and am seeing the behavior even though I have a new version now.
