### ISSUE TITLE
Add CircleCI or GitHub Action for Bento

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#115]
This idea comes from speaking with @nbrahms about reducing the cost of adopting Bento in CI. Two ideas that emerged were publishing a CircleCI orb or GitHub action.

**Comment by dlukeomalley** [comment]
Delaying this feature until we get further demand.

**Comment by dlukeomalley** [comment]
WIP by @underyx, adding to 0.9 kanban for tracking 💪

**Comment by underyx** [comment]
Overview of current state https://quip.com/QxhxABsUaXvg/Bento-Action-Walkthrough

**Comment by nbrahms** [comment]
It works!

**Comment by dlukeomalley** [comment]
See https://github.com/marketplace/actions/bento-check for the GitHub Action! :)
