### ISSUE TITLE
'bento check --formatter' usage is unclear

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#117]
Issue:

> -- I tried guessing "json" and it barfed with a stack trace
> -- searching on "format" in your README.md yields no hits
> -- I Googled on "bento check format json" and got no help on this (unsuprisingly if this is a new tool)

Proposed solution:
Include valid output formats in the help message of `--formatter`.

**Comment by nbrahms** [comment]
I'll add shortcuts and help text.

**Comment by nbrahms** [comment]
Fixed for 0.2.0

**Comment by dlukeomalley** [comment]
Confirmed in `0.2.0b3`. Closing!
