### ISSUE TITLE
Poor performance checking minified files

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#12]
We have some built, minified files that are ignored by git, but seen by eslint and therefore bento. 

Specifically eslint takes 106 seconds to run and outputs:
```
$ npx eslint --debug --no-eslintrc -c .eslintrc.yml .
...
✖ 884668 problems (861102 errors, 23566 warnings)
  698959 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by nbrahms** [comment]
Removing bug label here to separate out performance issues.

**Comment by dlukeomalley** [comment]
As of 0.3.0 we'll ignore minified files for performance reasons (inadvertently fixing this issue). @ievans please let us know if you continue to experience problems here or if 0.3.0 doesn't fix the issue as expected.
