### ISSUE TITLE
Consolidate .bento* files in .bento/

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#121]
Related to #67 and #79, it's nearing time to clarify our file structure and Bento install locations. This ticket is a proposal for the file structure, motivated by a user comment:

> having yet another yaml file in my source dir seemed annoying at first, but i liked how easy it was to add an exclusion. so toss up there

All Bento files should live in either `~/.bento/` if they're global, or `<project_path>/.bento/` if they are project specific. Example:

Current:
```
.bento/
    .venv
.bento.yml
.bento-whitelist.yml
.bentoignore
.eslintrc
```

Future:
```
.bento/
  archive.json
  config.yml
  tools.yml
  ignore
```

All top level `.bento*` files like `.bento-whitelist.yml` would be migrated down one directly level and take on the simpler name `archive.yml`. Same with our configuration file, which gains a clearer name than `bento.yml`.

Virtual environments and Bento specific dependencies are removed from the project entirely and are located instead in `~/.bento`

**Comment by nbrahms** [comment]
This is done for 0.8, with one exception:

We've left `.bentoignore` in the repo root, as it would otherwise be ambiguous as to which path relative file paths were based.
