### ISSUE TITLE
bento check should be able to set up project if bento init is not already done

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#124]
**Is your feature request related to a problem? Please describe.**
> bento check
✘ No Bento configuration found. Please run `bento init`.

**Describe the solution you'd like**
I would like bento check to ask me if I want to run `bento init` [y/n] and then drop me right into it.

**Comment by dlukeomalley** [comment]
Thank you for filing @ievans! We'll queue this up for discussion. How often are you running into this friction point?

**Comment by ievans** [comment]
A lot, I had a bunch of personal projects I wanted to try the tool on. So I cloned a bunch of them and then had to bento init, bento check for each.

**Comment by dlukeomalley** [comment]
@ievans I agree with the intent of this FR. On the r2c side we're updating `init` to automatically run `check` as one of its steps, which I think can hit much of the "quick start" desire (coming in 0.6). What do you think?

For background, we limit interactive Bento prompts to `bento init`. Maybe a `--quick-start` flag could work here, though I worry Bento tends to require project-specific configuration to provide meaningful results.

**Comment by ievans** [comment]
One thing I think we should definitely do is make sure that interactive sessions always explain somewhere how to run this non-interactively. So people no to pass `--noninteractive` when it's time to go to CI

**Comment by dlukeomalley** [comment]
Good feedback. We're trying to side-step that by not doing interactive sessions all together for our bread-and-butter that would programmatically be used. In the case of init, the current expectation (which could be wrong!) is that it's manually triggered. If you wanted to programmatically do it, you could just copy in Bento's config files and not need to run `init` at all.

Closing this issue for now! Let's see if it comes up again 🙏
