### ISSUE TITLE
Use a flag in telemetry to distinguish internal users

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#129]
**Is your feature request related to a problem? Please describe.**
Right now, internal usage of Bento and usage in QA tests makes for a lot of noise (we see thousands of events per day, and only a handful are external). I would like to be able to filter out all internal use. 

**Describe the solution you'd like**
Add a field to our telemetry data that distinguishes internal users (users with a @returntocorp.com, @r2c.dev email address or runs on our set of test repos)

Alternatively, a secret --internal flag that we (somehow) remember to set?

Other ideas welcome

**Comment by dlukeomalley** [comment]
@arashd Closing this as resolved and part of the larger usage and results data work we're doing. Let me know if you feel like it's not tracked elsewhere!
