### ISSUE TITLE
Telemetry endpoint fails for projects with many findings

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#13]
I ran Bento on Gatsby, and it reported ⚠ 93832 findings in 74.65 s.
After quitting out of `less`, I got the following error:

```
To suppress all findings run `bento archive`.
502 Server Error: Bad Gateway for url: https://test.massive.ret2.co/bento/api/v1/metrics/u/5d31fefde30357e2f40a46a079c014e26cb9be4c464dc507053531633511b8d7/
```

**Comment by ulziibay** [comment]
So, I see that `Logging 10297 data points` on the server, among many. I think posting a lot of data basically results in `502`

**Comment by dlukeomalley** [comment]
Because this is part of our initial install process I think this `502` issue needs to be corrected for early releases of bento. CC @nbrahms
