### ISSUE TITLE
New user’s email address does not populate in Mailchimp when surrounded by quotes

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#131]
If a user installs Bento and initializes for the first time, and enters their email address surrounded by quotes, they get the message:

“We were unable to subscribe you to the Bento mailing list, but will continue with installation. Please shoot us a note via support@r2c.dev to debug.”

I’m doing this on behalf of a user who encountered this, and I also verified myself using "pablo+test-25@r2c.dev".

**Comment by dlukeomalley** [comment]
@nbrahms This got fixed, right?

**Comment by nbrahms** [comment]
@dlukeomalley Correct. It was fixed in 0.2.1. ⛵️
