### ISSUE TITLE
bento should not display progress bars on non-interactive terminals

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#132]
**Describe the bug**
In CI, bento progress fills many vertical log lines, eg:
```
  r2c.eslint: |███            | 00:07, 🍜
  r2c.eslint: |███            | 00:07, 🍤
  r2c.eslint: |████           | 00:07, 🍤
  r2c.eslint: |████▌          | 00:07, 🍤
  r2c.eslint: |█████          | 00:08, 🍤
```

**Expected result**
Bento should detect that it is running in a non-TTY and not display progress bars.

**Comment by dlukeomalley** [comment]
Fixed in 0.6.1

**Comment by dlukeomalley** [comment]
@nbrahms I'm still seeing this as of 0.7 here: https://circleci.com/gh/jetbridge/jetkit-flask/253

Should the use of `--no-pager` suppress the progress bars? My inclination is that it shouldn't, but also seems like we need better logic / detection for CI environments.

**Comment by dlukeomalley** [comment]
This is queued up in 0.8, not 0.7. Re-adding `fixed` label
