### ISSUE TITLE
Bento telemetry discussion

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#141]
Problem:
At the moment, we can't track usage metrics such as churn and retention. We also can't reach out to users who dropped off and find out why.

Concerns:
- If we start collecting now, we don't stop over-collecting after GA
- Our language about telemetry scares users away
- Our language about telemetry is "deceiving"

Solution:
- Require email addresses pre-GA
- Clarify language around what we collect
- Allow users to opt out of telemetry post-GA

**Comment by dlukeomalley** [comment]
After discussing this we've updated our PRIVACY.md file and clarified the collection of usage vs. results data. Let me know if there is anything we've missed @arashd!
