### ISSUE TITLE
.bentoignore as an extension to the patterns in .gitignore

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#145]
**Is your feature request related to a problem? Please describe.**
I often analyze projects that have already carefully excluded non-code or non-important (eg vendored) code in their .gitignore. Currently I have to `cp .gitignore .bentoignore`

**Describe the solution you'd like**
For these projects, I would like to bento to by default use the .gitignore as the .bentoignore, and treat any patterns in .bentoignore as an extension.

**Comment by dlukeomalley** [comment]
@ievans To make this obvious user to he behavior, would offering a one-time import help? Something like:

> Do you want to use your .gitignore as the basis for what Bento ignores [Y/n]?

**Comment by ievans** [comment]
Yes, although I'd make it opt-out rather than opt-in if that makes sense

**Comment by dlukeomalley** [comment]
Yeah, I hear you. Would you expect that this opens a default editor (e.g. vim, emacs) to refine/edit the ignore? Similar to running `git commit`?

**Comment by dlukeomalley** [comment]
Related to #146

**Comment by ievans** [comment]
My initial expectation would be that it's not a one-time copy, but it permanently makes the `.bentoignore` an addition to the `.gitignore`

**Comment by dlukeomalley** [comment]
I'm going to queue this up for 0.5 or 0.6. Agreed that this is an issue that causes a poor initial experience. For a recent user, the time to run went from 12 minutes to 5 seconds after respecting what was in their `.gitignore`

> My public folder is part of my .gitignore. I wonder if .bento could safely assume that any folder or file path structure saved in the .gitignore is worth automagically adding to the .bentoignore file?

@ievans I've interviewed a few users now and the consensus seems to be that .bentoignore and .gitignore may be subtly different and that they'd like these to be maintained individually. Perhaps we can do is have Bento print out an informational note if we notice someone touches .gitignore but not .bentoignore (I hear you that keeping these files in sync may make sense for folks). Thoughts?

**Comment by ievans** [comment]
> Perhaps we can do is have Bento print out an informational note if we notice someone touches .gitignore but not .bentoignore (I hear you that keeping these files in sync may make sense for folks)

 I like this!

**Comment by dlukeomalley** [comment]
In 0.5, released next week, this will be addressed! `.benntoignore` will by default have a include statement bringing in `.gitignore` :)
