### ISSUE TITLE
Bento Init design improvements

### ISSUE THREAD

**Issue by dan5382** [returntocorp/bento#146]
Making our 'init' command an 11 star experience. 
**why?** 
1. We’ve received feedback on the overwhelming number of checks that people see the first time they run bento check
        a. They don’t know where to start in the possibly hundreds or thousands of checks that display
        b. There is often nuggets of goodness that are hard to find (e.g. JB’s unsafe yaml load buried in         
            unused import errors, Daghan’s demo where he found a real issue in his codebase)

2. Users aren’t sure what archive is or that it is a function they can execute and should execute in the face of a lot of checks
3. We assumed or expected people to run Bento on new projects, but in practice every user has installed Bento on a pre-existing project that is likely to have existing results
4. The first time experience for most Authority users is a poor one, the tool isn’t differentiated from other linters in this regard because they too print out a ton of errors to manually triage (distracting from a “wow” onboarding experience) 

What? 
*Evolve bento result formatting* to be more like the r2c inbox, organizing checks by priority (?) and category for three common states: 
1. No results to display
2. A handful of results
3. A ton of results (100+, 1k+, 10k+)

**Goals**
1. [primary] Get your user quickly back to coding
2. [primary] User’s quickly identify the most important issues to address (vs. those they should archive)
    a. SMART
    b. auto archive unless important
3. [secondary] User’s know the next step they should or could take with Bento (related to https://quip.com/KlEuADnC7TaC)

**Def of Done**
- [x] Flow is agreed upon
- [x] Content is agreed upon and complete
- [x] Views are mocked up with the current language
- [ ] Mocks have been user tested 
- [ ] changes implemented based on user feedback

**Comment by dlukeomalley** [comment]
@dan5382 May I close this issue given our mocks and currently planned work?

**Comment by dan5382** [comment]
yup sounds good to me!
