### ISSUE TITLE
`bento check` should show all running core-tool plugins (e.g. flake8-debugger)

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#148]
We've done a lot of work to choose flake8 and eslint plugins, but that work isn't highlighted when you run `bento check`. It's important that we communicate our value and work to end-users, and need some way to show that we're doing a lot of work behind the scenes. Historically we've done this through our progress bars.

**Comment by dlukeomalley** [comment]
@nbrahms Did this get implemented and/or is it part of the Bento init/check improvement work slated for this week?

**Comment by nbrahms** [comment]
Hi Luke,

This is slated for 0.6.

Best,
Nathan

**Comment by dlukeomalley** [comment]
Roger! Adding to 0.6 explicitly then 👍

**Comment by dlukeomalley** [comment]
As we've added more and more of our custom tools over time, the need to break apart the flake8 plugins to demonstrate the work we're doing has decreased. For now we'll close this issue and revisit if we receive future feedback.
