### ISSUE TITLE
document next steps from bento check

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#149]
**Is your feature request related to a problem? Please describe.**
Right now after you run bento check you see the following:
```
To suppress all findings run `bento archive`.
```
It's unclear what other actions you can take from this point.

**Describe the solution you'd like**

1. Take out the whitespace in the report so that it's obvious how you refer to a check, can be copied to the clipboard with a single double-click, and support either syntax to bento enable/disable:
`r2c.bandit     B602` -> `r2c.bandit.B602` (can still hyperlink the whole thing)

2. To suppress these findings (but not future ones) run `bento archive`; to turn off a specific check run `bento disable r2c.bandit.B602`; to ignore a file or folder, run `bento ignore <path>`

* This clarifies that you are not suppressing future findings
* It shows how to enable/disable a specific check without having to read the docs

**Comment by dlukeomalley** [comment]
Related to #146 improvements

**Comment by dlukeomalley** [comment]
Fixed in 0.7!
