### ISSUE TITLE
Flake8 `B008:` incorrectly includes a colon

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#154]
Related issue: if you want to ignore the flake8 `B008`, you have to add it to the .bento.yml as
```
- "B008:"
```
due to the colon on the end (you get an error if you don't use quotes).

Might be worth submitting a fix upstream.

(The web framework I use ([fastapi](https://github.com/tiangolo/fastapi)) heavily violates B008 for dependency injection.)

_Originally posted by @dmontagu in https://github.com/returntocorp/bento/issues/152#issuecomment-550499421_

**Comment by nbrahms** [comment]
I agree that the correct solution is to submit a PR to bugbear.

**Comment by minusworld** [comment]
Here's the line:

https://github.com/PyCQA/flake8-bugbear/blob/master/bugbear.py#L500

Also went ahead and submitted a PR for them.

**Comment by dlukeomalley** [comment]
Fixed in upcoming 0.9 release! 🎉
