### ISSUE TITLE
Concatenate tool and check-id 

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#156]
Rather than displaying `r2c.eslint no-console` in our stylish and clippy format, there have been several requests to render `r2c.eslint.no-console` and to have stylish, clippy, and our enable/disable check display and/or respect that format.

**Comment by ievans** [comment]
@dlukeomalley N.B. that many tools may have periods in their check names, so any fix should be aware of that

**Comment by dlukeomalley** [comment]
We're backing away from this for the time being given naming issues like the above, as well as how we've chosen to display tools and check IDs in Bento's histogram.
