### ISSUE TITLE
Output is hard to read on light terminal themes

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#160]
Users have a mix of light and dark terminals, and we over-optimize for dark themes right now. @ievans is a great canary user because he uses a light terminal and is color-blind.

From #101:

> (3) The blue text is unreadable on my terminal, does anyone else have this problem (@dlukeomalley ?)

As part of #146, we should consider this and resolve this ticket.

**Comment by nbrahms** [comment]
@dlukeomalley I'm wondering if you meant the standard dark theme.

Here's the output of bento check on iterm2's standard dark, standard light, solarized dark, and solarized light themes:

![image](https://user-images.githubusercontent.com/2490631/68413282-cdc60f00-0142-11ea-9499-77f69ed30851.png)

The blue does seem hard to discern in the standard dark theme. I'm wondering what we'd replace it with, however. We can always print in the default foreground color, but I've found this gets lost in terminal output. Other colors seem to be overloaded in terms of meaning (we use red, yellow, and green for the concepts of failure, warning, and success, respectively), and cyan has this same issue, just on the opposite color theme.

I'd be curious if @dan5382 has suggestions?

**Comment by dan5382** [comment]
is there anyway to detect whether its a light or dark theme they are using and use color appropriately for that?

**Comment by dan5382** [comment]
funny though a brighter blue might be the direct solution here.

**Comment by ievans** [comment]
Does the blue have any specific meaning? None of the testing frameworks I've seen use blue. I would propose sticking to the default color. Here's what it looks like on my terminal:

![image](https://user-images.githubusercontent.com/409041/68422507-30c0a180-0155-11ea-9cf9-74e5f1889e4f.png)

**Comment by dmontagu** [comment]
> is there anyway to detect whether its a light or dark theme they are using and use color appropriately for that?

I was curious about this, it looks like the answer is that there [just isn't really a standard convention](https://unix.stackexchange.com/questions/245378/common-environment-variable-to-set-dark-or-light-terminal-background).

It's too bad ANSI color codes don't encode high vs. low contrast, instead of "bright" vs normal...

**Comment by nbrahms** [comment]
> Does the blue have any specific meaning? None of the testing frameworks I've seen use blue. I would propose sticking to the default color. Here's what it looks like on my terminal:

@ievans , the intent, at least, is to indicate a status update with the blue color. So the color scheme mapping is:

- default - generic information
- blue - status update
- green - success
- yellow - warning
- red - error

Re. the testing frameworks you've used, have any of them indicated progress or status in any way?

**Comment by nbrahms** [comment]
> funny though a brighter blue might be the direct solution here.

@dan5382 I went ahead and tried this out. For the light and dark themes it works well, although the solarized themes render "bright" as "default" text. Might be a reasonable compromise, however.

**Comment by ievans** [comment]
@nbrahms the testing frameworks I'm thinking of (jest IIRC) usually use emoji or unicode to indicate status, such as “✓” U+2713, sometimes in green (so status is binary, either success or failure, and default color until then)

**Comment by dan5382** [comment]
@nbrahms the color choices i was starting with i was actually testing it on light and dark for accessibility reasons but some of the ideas here using emoji's etc are a great addition, as most emoji's were made to be accessible

**Comment by deifactor** [comment]
Emojis also will run into issues if the user has weird font setup, so we shouldn't use them as the only way to recognize whether something was successful or not.

**Comment by dlukeomalley** [comment]
This is being addressed in 0.7! We now use colors that work across a wider range of terminal backgrounds and rely more heavily on the terminal's default text color, the use of dim, the use of bold, and the use of underlines to give context and meaning to Bento's output.
