### ISSUE TITLE
Clicking filename + line number should open default editor

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#164]
**Is your feature request related to a problem? Please describe.**
When I see errors in Bento, I have to remember the file path and line number, open my editor and navigate there.

**Describe the solution you'd like**
I'd like to click and be dropped into the file at the right location, if possible.

**Comment by ievans** [comment]
More generally, is there a way we can open $EDITOR and have a queue of issues that a user can jump back and forth between? I feel there might be a way to do this at least for emacs (cc @deifactor)

**Comment by arashd** [comment]
I've tested on iTerm2 and Terminal with and without `--formatter clippy`. cc: @dlukeomalley since you mentioned having seen this work, do you remember if you had to change anything?

**Comment by dmontagu** [comment]
For what it's worth, in PyCharm, it appears to be enough to just print the full path to the file -- it generates a link for you based on that. Adding `line 14` or similar on the same line as the full path to the file makes the link take you to the correct line, too.

**Comment by dlukeomalley** [comment]
This already works for me with the clippy format, but I have default file handlers setup for files ending with a code identifier (e.g. .py, .js)

See https://stackoverflow.com/questions/43665346/can-somebody-explain-how-to-make-vscode-the-default-editor-on-osx/43665710

With the clippy format, vscode even opens to the right file, line, and character for me 💪 Is this maybe just a documentation issue for us?

**Comment by dmontagu** [comment]
Actually, for what it's worth, I was wrong about PyCharm -- you specifically have to have the output take precisely the form:
```
File "</absolute/path/to/file.py>", line <number>
```
to get it to highlight automatically.

**Comment by nbrahms** [comment]
@daghan Can you comment? I seem to recall that you had VsCode integration working so that file clicking worked properly...

**Comment by kurtmcintire** [comment]
Command+clicking works with VSCode. I don't get automatic highlighting on the issue line, however.

**Comment by dlukeomalley** [comment]
Hi all, I'm not sure this issue has a fix. Command clicking works within iTerm (and related modern terminals) and the specific handling of file paths is OS-dependent, and user configurable on Mac. I don't think Bento itself has much control here over how file paths are opened.

If the above is true, I'd like to close this issue and reopen more focused documentation tickets.

**Comment by ievans** [comment]
idea: Onboarding (init) could suggest/demo this feature for the user
