### ISSUE TITLE
Provide aggregate result counts

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#168]
When users are presented with a large number of findings it's overwhelming. To help position them, there have been requests for some kind of summary or high-level overview of the types of errors that are present and in what quantity. An action users may take is to disable checks with large number of findings that they don't agree with.

This work is partly related to #146 and upcoming `bento check` refinements.

Motivating quote:

> * When I first ran it, I had an absurd amount of errors ~7k. After several iterations I was able to get that number down. Would have been nice to have a histogram of errors. Ex: 6 style checks accounted for ~6k of the errors

**Comment by DrewDennison** [comment]
@nbrahms can this be closed?

**Comment by nbrahms** [comment]
@dlukeomalley This will be provided in 0.6 :)
