### ISSUE TITLE
bento init completes successfully even if project contains no supported languages

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#170]
I'm filing this as a bug largely because it is highly confusing to users and is a missed opportunity to guide a user in the right direction / to the right next step.

If a project contains no supported languages, it appears that init runs successfully, but future commands fail with the following errors:

```shell
There was an exception Number of processes must be at least 1
```

```shell
Bento can't identify this project.
```

**Comment by nbrahms** [comment]
Hi @dlukeomalley 

Can you submit steps to reproduce this issue?

Doing the following:
- Make new git project
- Add a commit
- Run bento init

I get:
```
(bento-core) ➜  foo git:(master) ✗ bento init
✘ Bento can't identify this project.
```

**Comment by dlukeomalley** [comment]
@nbrahms I haven't been able to repo beyond a screenshot from a user. In the absence of reproducing, the error message `✘ Bento can't identify this project.` doesn't indicate to me what happened, and what I should go do next. As an easy compromise can we update its language while I try to reproduce?

**Comment by dlukeomalley** [comment]
This is also improved by @dan5382's Bento init work. If there are no supported languages, I think it's worth us erroring out with something like:

> ✘ Bento didn't detect any supported languages in this project. Language support is discussed on the Bento README.md [link]. If this is in error please let us know by filing an issue [link].

**Comment by nbrahms** [comment]
OK, in that case my proposal is to punt this issue, and just make sure we incorporate what we've learned here into the new `init` design.

**Comment by dlukeomalley** [comment]
That's fine. Explicitly moving to 0.6 release then with your other bento init work.

**Comment by dlukeomalley** [comment]
@nbrahms Is this addressed by https://github.com/returntocorp/bento/issues/177?

**Comment by nbrahms** [comment]
Hi @dlukeomalley ,

Given that we haven't been able to reproduce the issue, it's hard for me to determine if the original problem has been addressed, to be honest.

**Comment by dlukeomalley** [comment]
Let's close for now then :)
