### ISSUE TITLE
bento check non-blocking flag

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#172]
**Is your feature request related to a problem? Please describe.**
I'm trying to run `bento check` in CI to prove its value before making it block my merges, but it's exiting with a non-zero exit code whenever it finds any results.

**Describe the solution you'd like**
I'd like to run `bento check --non-blocking` to see bento's results printed to the console, but not failing my build.

**Comment by ulziibay** [comment]
I honestly think we should jam in `--experimental` into CI too

**Comment by dlukeomalley** [comment]
@arashd Just keeping things simple, are you open to us skipping this feature in favor of `bento check || true`?

**Comment by dlukeomalley** [comment]
Keeping things simple for now :) Let's stick with `|| true`
