### ISSUE TITLE
flake8 B001 is redundant with E722

### ISSUE THREAD

**Issue by daghan** [returntocorp/bento#174]
## Overview
Both checks catch bare 'except' cases. But B001 has better explanation. So we should disable E722 by default.

## Current Behavior
182:9  error   Do not use bare `except:`, it also catches unexpected events like memory errors, in... r2c.flake8     B001
182:9  error   do not use bare 'except'                                                               r2c.flake8     E722

## Steps to Reproduce
git clone https://github.com/daghan/aspen.py.git
bento check

## Possible Solution
Disable E722

## Additional Context
Bento version (run `bento --version`): bento/0.4.0
Operation system (e.g. Ubuntu 18.04): MacOS Catalina
Any other context that would help us reproduce or understand the issue:

**Comment by nbrahms** [comment]
👋  Fixed in 0.5
