### ISSUE TITLE
Disable flake8 rule E306 

### ISSUE THREAD

**Issue by daghan** [returntocorp/bento#175]
## Overview
This rule is about blank lines: `expected 1 blank line before a nested definition, found 0  `
And per our blog we don't focus on blank likes 

## Current Behavior
rror: r2c.flake8.E306 https://lintlyci.github.io/Flake8Rules/rules/E306.html
   --> aspen/request_processor/__init__.py:67:9
    |
 67 |   def safe_getcwd(errorstr):
    |
    = note: expected 1 blank line before a nested definition, found 0     

## Steps to Reproduce
Just run bento on this repo
https://github.com/daghan/aspen.py

## Possible Solution
> Do you have an idea for how to address the issue or feedback?

## Additional Context
Bento version (run `bento --version`):
Operation system (e.g. Ubuntu 18.04):
Any other context that would help us reproduce or understand the issue:

**Comment by dlukeomalley** [comment]
This has been resolved in 0.6!
