### ISSUE TITLE
Bento output is difficult to read in CircleCI output

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#178]
## Overview
Bento output is difficult to read in CircleCI output

## Current Behavior

![image](https://user-images.githubusercontent.com/409041/69170970-df4ad780-0aaf-11ea-910f-5482cd19a1f7.png)

## Steps to Reproduce

1. Run a job using bento on circleCI

## Possible Solution
Maybe when in CI environments, pick a different terminal width?

**Comment by dlukeomalley** [comment]
@ievans with the switch to a new output format (`clippy`), is this still an issue for you?

**Comment by dlukeomalley** [comment]
@ievans Closing this out for because of our change to `clippy` by default. Please let us know if this is still challenging for you with that output format.
