### ISSUE TITLE
Add ability to ignore files or directories

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#18]
You can't ignore folders (have to fallback to the ignore config for each tool), which can have awful performance impacts like #12. Suggestion: it should be easy to `bento ignore <paths>` or use the gitignore as a start

**Comment by dlukeomalley** [comment]
Moving from #78 

> **Is your feature request related to a problem? Please describe.**
> It would be nice to be able to exclude some files from analysis.
> 
> For example, running over [pydantic](https://github.com/samuelcolvin/pydantic), a handful of issues are flagged in the docs examples (which are .py files), but that is because not all docs examples are self-contained. These files are excluded from linting in the existing CI jobs.
> 
> I recognize that I could just use `bento archive` to ignore those issues, but I'd like to 1) preempt any issues being flagged in those files in the future, and 2) avoid wasting time analyzing those files on every run.
> 
> **Describe the solution you'd like**
> Something analogous to .gitignore.

**Comment by dlukeomalley** [comment]
Another request came in today for this / related features:

> -- the linter ran on my virtualenv environment, which I slotted inside my repo directory after “clone”, which caused a ton of third party library junk to get included in the report (you could filter this out with the VIRTUAL_ENV environment variable)

**Comment by dlukeomalley** [comment]
The ability ignore files or directories would have contributed to a cleaner resolution to https://github.com/returntocorp/bento/issues/81#issuecomment-541208166

**Comment by dlukeomalley** [comment]
Additional feedback:

> To elaborate, we use a complex project structure that integrates open source code with our own, and is a combination of several different languages. So, what I would really like is the ability to just scan a few files or directories, rather than the whole project. The fix would be simple -- something like a .gitignore for bento -- and it looks like there is an open issue (https://github.com/returntocorp/bento/issues/18) that might solve my problem.

**Comment by dlukeomalley** [comment]
Additional feedback:

> If I can run it on a single file AND filter out directories I don't want it to scan, I would use it regularly

**Comment by dlukeomalley** [comment]
@ievans @dmontagu This will be part of our upcoming release (0.3.0). Thank you for filing this issue!
