### ISSUE TITLE
Flask best practices checks

### ISSUE THREAD

**Issue by ulziibay** [returntocorp/bento#180]
**Is your feature request related to a problem? Please describe.**
Add Flask best practice checks

**Describe the solution you'd like**

1) Even simple recommended directory structure for Flask Apps (separating model, blueprint, API etc.), Basically way to enforce: https://flask.palletsprojects.com/en/1.1.x/tutorial/layout/
2) Blueprint best practices: e.g. recommend using Blueprint when people are doing so much computation in @app.route handlers
3) Enforce MVC  separation in Flask
4) url_for method checks for undeclared routes
5) Detect duplicate Javascript in flask templates

**Comment by dlukeomalley** [comment]
@ulziibay @minusworld Closing this in favor of the checks articulated at https://github.com/returntocorp/sgrep-rules/issues

Let me know if you'd like to keep tracking this here!
