### ISSUE TITLE
Add --ignore flag to check command

### ISSUE THREAD

**Issue by ulziibay** [returntocorp/bento#181]
**Is your feature request related to a problem? Please describe.**
Ignore a directory or file while running `bento check`

**Describe the solution you'd like**
Adds the given DIR to .bentoignore

Add a `--ignore <PATH>` flag to `bento check`.

**Comment by dlukeomalley** [comment]
@ulziibay Thanks for filing this feature request! When I first read this, I imagined a temporary ignore flag like `--ignore`. Did you intend for this to be changing the configuration of Bento permanently, by adding the specified file to `.bentoignore`?

**Comment by dlukeomalley** [comment]
Marking this as stale for now, please let me know if there are any other details that would help us make a decision about this feature! Particularly helpful would be a workflow you tried to do that you weren't able to given current Bento.

My thinking is that between `.bentoignore` and running `bento check <PATH` (effectively a whitelist feature) there are quite a few options available to users and that this becomes a much smaller edge case.
