### ISSUE TITLE
Python 3 best practices

### ISSUE THREAD

**Issue by ulziibay** [returntocorp/bento#182]
**Is your feature request related to a problem? Please describe.**
while doing python 2.7 -> 3: migration, bento should alerts about python2 deprecated API, or python3 best practice!  

**Describe the solution you'd like**
This prevents having to do end to end testing during migration from python 2 to python 3

**Comment by dlukeomalley** [comment]
@ulziibay Thanks for filing this! Do you have specific examples of the deprecated APIs or Python 3 best practices the team would be able to help with?

**Comment by ulziibay** [comment]
@ievans created https://returntocorp.quip.com/XRNGA8fXgRAC/sgrep-python-compatibility-checks, which would be great to check for!

**Comment by dlukeomalley** [comment]
@ulziibay @minusworld Closing this in favor of the checks articulated at https://github.com/returntocorp/sgrep-rules/issues

Let me know if you'd like to keep tracking this here!
