### ISSUE TITLE
`bento init` fails if path contains a space

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#183]
## Overview

can't bento init if path contains a space

## Current Behavior

`$ cd <...>/Downloads/path with space`
`$ bento init`
`⚠ Could not execute "<...>/Downloads/path with space/.bento/flake8/bin/activate; python -m pip install -q flake8 flake8-json flake8-bugbear flake8-builtins flake8-debugger flake8-executable":`

## Possible Solution

Fix it. Also there should probably be an integration test for this.

**Comment by dlukeomalley** [comment]
Thanks for filing @ievans! Queuing this up for a quick fix.

**Comment by dlukeomalley** [comment]
Shipping in 0.6!
