### ISSUE TITLE
Render_template('img_browser') is not being caught

### ISSUE THREAD

**Issue by ulziibay** [returntocorp/bento#188]
[last.log](https://github.com/returntocorp/bento/files/3890584/last.log)
## Overview
> Briefly describe the issue and your expected behavior
render_template('img_browser') should trigger the check! Its not at the moment!
## Current Behavior
> Describe the actual behavior, and provide the content of `~/.bento/last.log` if possible. Screenshots and text dumps are particularly helpful.

## Steps to Reproduce

1. pip install bento-cli==0.6.0b1
2. Add Render_template('img_browser')
3. bento check

## Possible Solution
> Do you have an idea for how to address the issue or feedback?

## Additional Context
Bento version (run `bento --version`):
Operation system (e.g. Ubuntu 18.04):
Any other context that would help us reproduce or understand the issue:

**Comment by minusworld** [comment]
Is this related to the jinja templates?  I don't think the unescaped file extension check made it into Bento yet.  That check was released in 0.2.0 of the flake8-flask plugin, and since we were trying to align quickly on naming, I didn't push for it.

**Comment by dlukeomalley** [comment]
Given @minusworld's comments above and the recent 0.7 release, I am closing this ticket for now. @ulziibay, please let me know if this problem persists!
