### ISSUE TITLE
flake8-builtins A003 triggers on SQLAlchemy classes that follow convention

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#197]
## Overview
flake8-builtins A003 triggers on SQLAlchemy classes that follow SQLAlchemy convention of using the class property `id` for private key fields. We discussed this in #bento on the community Slack.

> I just name my PK column `id` in my database
> I think that's normal
> the class properties should match your column names

This check is perceived as noisy and/or not-applicable in this case. Users are following the convention set for them by the framework.

## Current Behavior
```shell
error: r2c.flake8.A003 https://lintlyci.github.io/Flake8Rules/rules/A003.html
   --> jetkit/db/__init__.py:50:5
      |
   50 |   id = Column(Integer, primary_key=True)
      |
    = note: "id" is a python builtin, consider renaming the class attribute
```

## Additional Context
Bento version (run `bento --version`): 0.6.1

**Comment by dlukeomalley** [comment]
After working more with flake8-builtin and some light user feedback, my vote is just remove this plugin altogether.

**Comment by minusworld** [comment]
https://github.com/returntocorp/bento-core/issues/390
