### ISSUE TITLE
bento “command not found” error after pip-installing

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#2]
I used DigitalOcean to spin up a fresh Ubuntu instance: 
Ubuntu 18.04.3 (LTS) x64
and used very lightweight specs: $5/mo, 1 GB / 1 CPU, 25 GB SSD disk, 1000 GB transfer

Ubuntu already had Python 3.6.8 installed, so I installed `pip` using:
`python3-pip` and then ran `pip3 install r2c-bento`.

`pip3` reported successful installation. Then I tried to run Bento using `bento` and this error came up:

```
pablo@ubuntu-s-1vcpu-1gb-sfo2-01:~$ bento
bento: command not found
```

Here’s the `$PATH`:
```
pablo@ubuntu-s-1vcpu-1gb-sfo2-01:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

Let me know if you want to log in to this machine.

**Comment by pabloest** [comment]
I reproduced this on another fresh Ubuntu installation. The behavior reported in the original issue remains, however logging out of the ssh session and logging back in seems to fix the issue.
```
Last login: Tue Oct  1 17:35:40 2019 from 136.24.226.10
pablo@ubuntu-s-1vcpu-1gb-sfo2-01:~$ which bento
/home/pablo/.local/bin/bento
pablo@ubuntu-s-1vcpu-1gb-sfo2-01:~$ bento --version
bento/0.0.19
```

**Comment by dlukeomalley** [comment]
@pabloest May I close this issue? From reading your description, this appears to be a `pip` and environment related bug that I'm not sure we'll be able to address.

**Comment by pabloest** [comment]
Yep, sounds fine to me.
