### ISSUE TITLE
r2c-lib errors while pip installing bento

### ISSUE THREAD

**Issue by daghan** [returntocorp/bento#20]
When I install bento via ` pip install --force r2c-bento==0.1.0b5`

I get these python error messages:
>ERROR: r2c-lib 0.0.16 has requirement certifi==2019.3.9, but you'll have certifi 2019.9.11 which is incompatible.
ERROR: r2c-lib 0.0.16 has requirement docker==3.7.0, but you'll have docker 3.7.3 which is incompatible.
ERROR: r2c-lib 0.0.16 has requirement gitpython==2.1.11, but you'll have gitpython 2.1.14 which is incompatible.
ERROR: r2c-lib 0.0.16 has requirement requests==2.21.0, but you'll have requests 2.22.0 which is incompatible.
ERROR: r2c-lib 0.0.16 has requirement semantic-version==2.6.0, but you'll have semantic-version 2.8.2 which is incompatible.
ERROR: r2c-lib 0.0.16 has requirement urllib3==1.24.3, but you'll have urllib3 1.25.3 which is incompatible.
ERROR: r2c-lib 0.0.16 has requirement websocket-client==0.55.0, but you'll have websocket-client 0.56.0 which is incompatible.
ERROR: r2c-cli 0.0.21 has requirement certifi==2019.3.9, but you'll have certifi 2019.9.11 which is incompatible.
ERROR: r2c-cli 0.0.21 has requirement docker==3.7.0, but you'll have docker 3.7.3 which is incompatible.
ERROR: r2c-cli 0.0.21 has requirement gitpython==2.1.11, but you'll have gitpython 2.1.14 which is incompatible.
ERROR: r2c-cli 0.0.21 has requirement requests==2.21.0, but you'll have requests 2.22.0 which is incompatible.
ERROR: r2c-cli 0.0.21 has requirement semantic-version==2.6.0, but you'll have semantic-version 2.8.2 which is incompatible.
ERROR: r2c-cli 0.0.21 has requirement urllib3==1.24.3, but you'll have urllib3 1.25.3 which is incompatible.
ERROR: r2c-cli 0.0.21 has requirement websocket-client==0.55.0, but you'll have websocket-client 0.56.0 which is incompatible.
ERROR: py2neo 4.2.0 has requirement urllib3[secure]<1.25,>=1.23, but you'll have urllib3 1.25.3 which is incompatible.

Info about my env:
`pip --version`
pip 19.2.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

`python --version`
Python 3.7.4

**Comment by nbrahms** [comment]
I reproduced this by pinning `r2c-lib` to version 0.0.15, but none of this prevented me from running `bento` as expected.

This looks to be a problem mostly with the requirements file of the `r2c-lib` package, not `r2c-bento`. Definitely should be fixed, but on `r2c-lib`, not `r2c-bento`. I'll cross-file there.

**Comment by dlukeomalley** [comment]
I'm comfortable with the cross-filing and somewhat comfortable with closing this issue. I worry it's alarming and confusing that installing bento spits out (non-blocking) errors. What is the timeline for fixing r2c-lib and by extension upstream consumers like bento?
