### ISSUE TITLE
Disable flake8 rule F841

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#201]
Unused local variable fires often and thus far has not been positively received by users. This issue proposes disabling it, as often it's not a bug though it's (universally?) acknowledged as code smell.

```shell
error: r2c.flake8.F841
     --> call_server/political_data/__init__.py:60:5
      |
   60 |       except (ImportError, AttributeError) as e:
      |
      = note: local variable 'e' is assigned to but never used
```

## Steps to Reproduce

1. git clone https://github.com/opensourceactivismtech/call-power/
2. `bento check`

## Possible Solution
Disable F841

## Additional Context
Bento version (run `bento --version`): 0.7.0b2

**Comment by ievans** [comment]
I would support putting this under a general "unused/deadcode" category that can be enabled/disabled enmasse.

**Comment by minusworld** [comment]
https://github.com/returntocorp/bento-core/pull/444
