### ISSUE TITLE
Move Bento's .venv to global ~/.bento directory

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#206]
We've had a few issues related to `<project>/.bento/.venv` that would be resolved by putting Bento's dependencies in `~/.bento/.venv/<project-id>/...`:

> It was clever enough to add itself to .gitignore but not .dockerignore. We frequently package our tools in Docker containers, and so all 122MB of the `.bento/` directory was sent into the build context (and theoretically would have been copied into the image if we had  `ADD * .`).

> do not load a bunch of python libraries into `.bento` folder within the project, since it makes the project heavier (longer Docker build time), and corrupts PyCharm's search across the project files (because you start seeing a lot of search hits from libraries, not from your own project, which is not desirable).

**Comment by nbrahms** [comment]
This is done in 0.8.

All projects now share a virtual environment per tool, located in `~/.bento`.
