### ISSUE TITLE
Check parent directories for .bento* files

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#21]
Similar to git behavior, it would be nice for bento to look in parent directories to see if the bento project is initialized. iirc, this matches the behavior of tools like docker-compose.

Currently we show the following:
```
✘ No Bento configuration found. Please run bento init.
```

CC @ievans for the original request

**Comment by deifactor** [comment]
Taking over this per in-person conversation with Tru.

Another feature that should also go in this: `--root $DIR` to specify the path to the directory, for if you want to run Bento *outside* of the repo root for some reason (CI?).

**Comment by dlukeomalley** [comment]
Thanks @deifactor! Looking forward to the feature 🙂

**Comment by dlukeomalley** [comment]
This will ship as part of 0.3.0! Thanks @deifactor 🎉
