### ISSUE TITLE
Disable flake8 E999

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#213]
## Overview
I'd like to raise a discussion on r2c.flake8.E999

## Current Behavior

E999 bundles a couple messages, which although they are not purely style, are also not truly bugs (at least, a TabError isn't):
note: TabError: inconsistent use of tabs and spaces in indentation
note: invalid escape sequence '\*'

## Steps to Reproduce

1. git clone https://github.com/signalapp/signal-webrtc-ios
2. bento init && bento check

## Possible Solution
Disable E999 or rewrite it.

## Additional Context
Bento version (run `bento --version`): bento 0.6.2
Operation system (e.g. Ubuntu 18.04): macOS

**Comment by dlukeomalley** [comment]
Queuing up for 0.8

**Comment by nbrahms** [comment]
Hi @ievans ... E999 is not actually a check per se, but an error code returned by flake8. This typically occurs when flake8 can not parse the python code.

IMO we should generally be alerting on unparseable code.

**Comment by ievans** [comment]
@nbrahms makes sense. Perhaps we could roll it up in the sloc metrics? Reporting like `2.5k Python, 300 lines unparsable`

**Comment by nbrahms** [comment]
@dlukeomalley @ievans Closing this issue for now. @ievans, could you open a feature request ticket for any follow-up items you have?
