### ISSUE TITLE
Bento double-prints the context for some hadolint errors

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#214]
## Overview
> Briefly describe the issue and your expected behavior
Hadolint includes context in its message, so we double-print the context.

## Current Behavior
> Describe the actual behavior, and provide the content of `~/.bento/last.log` if possible. Screenshots and text dumps are particularly helpful.
Bento double-prints the context.

```
==> Bento Summary
error: r2c.hadolint.DL1000
     --> Dockerfile:8:7
      |
    8 |   COPY .
      |
      = note: /dev/stdin:8:7:
  |
8 | COPY .
  |       ^
unexpected end of line. At least two arguments are required for COPY
```

## Steps to Reproduce

1. Create a Dockerfile with a line that doesn't have RUN, ENTRYPOINT, etc.
2. Enable Hadolint
3. Run `bento check`

## Possible Solution
> Do you have an idea for how to address the issue or feedback?
Detect when the context is printed by hadolint and exclude it.

## Additional Context
`bento/0.7.0b9`
MacOS

**Comment by dlukeomalley** [comment]
Fixed for 0.8 (release mid-Jan).
