### ISSUE TITLE
Remove leading spaces in clippy code snippets

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#221]
## Overview
Our clippy formatter doesn't strip or left-indent code snippets, which causes nested code to be harder to read when `bento check` runs.

## Possible Solution
Please strip leading whitespace from code snippets, being careful to respect relative indentation for multi-line snippets.

**Comment by nbrahms** [comment]
Fixed for 0.8.

It's useful to note that this means that our character number indicators are now useless. I've removed them.
