### ISSUE TITLE
Commit hook fails when using Fork, the Git(hub) GUI

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#224]
## Overview
I set up Bento as a pre-commit hook. When trying to commit code via [Fork](https://git-fork.com/), I get the following error (this is shown in a Fork pop-up message): 
```
Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 88, in <module>
    exit(main())
  File ".git/hooks/pre-commit", line 82, in main
    return retv | _subprocess_call(_exe())
  File ".git/hooks/pre-commit", line 61, in _exe
    raise FatalError("`bento` not found.")
__main__.FatalError: `bento` not found.
```
Here’s my `.git/hooks/pre-commit` file: 
```
#!/usr/bin/env python3
"""File generated by bento. Roughtly lifted from pre-commit"""
from __future__ import print_function

import distutils.spawn
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


BENTO_TEMPLATE_HASH = "3a04e0f0cd9243d20b1e33da7ac13115"


class FatalError(RuntimeError):
    pass


def _norm_exe(exe):
    """Necessary for shebang support on windows.

    lifted from pre-commit which roughly lifted from `identify.identify.parse_shebang`
    """
    with open(exe, "rb") as f:
        if f.read(2) != b"#!":
            return ()
        try:
            first_line = f.readline().decode("UTF-8")
        except UnicodeDecodeError:
            return ()

        cmd = first_line.split()
        if cmd[0] == "/usr/bin/env":
            del cmd[0]
        return tuple(cmd)


def _run_legacy():
    legacy_hook = os.path.join(HERE, "pre-commit.pre-bento")
    if os.access(legacy_hook, os.X_OK):
        cmd = _norm_exe(legacy_hook) + (legacy_hook,) + tuple(sys.argv[1:])
        proc = subprocess.Popen(cmd)
        proc.communicate(None)
        return proc.returncode, None
    else:
        return 0, None


def _validate_config():
    """
        Do validation here
    """
    pass


def _exe():
    if distutils.spawn.find_executable("bento"):
        return ("bento", "--agree", "check", "--staged-only")

    raise FatalError("`bento` not found.")


def _rev_exists(rev):
    return not subprocess.call(("git", "rev-list", "--quiet", rev))


if sys.version_info < (3, 7):  # https://bugs.python.org/issue25942

    def _subprocess_call(cmd):  # this is the python 2.7 implementation
        return subprocess.Popen(cmd).wait()


else:
    _subprocess_call = subprocess.call


def main():
    retv, stdin = _run_legacy()
    try:
        _validate_config()
        return retv | _subprocess_call(_exe())
    except KeyboardInterrupt:
        return 1


if __name__ == "__main__":
    exit(main())
```

Here’s my `~/.bento/last.log` (though I believe Bento may not have run):
https://gist.github.com/pabloest/fc748b8c2ad2ba3bc0735a2b2136078c

## Additional Context
Bento version: 0.7.0
macOS 10.14.6
Fork version: 1.0.84

**Comment by dlukeomalley** [comment]
@pabloest Thanks for filing this and chatting with me in person. Filling out some context here for others: From logs it appears Fork doesn't have access to the global installs (including Bento). From that perspective, this isn't a Bento issue, but something specific to Fork. Given that, I'd like to close this issue and mark as `wont-fix`. If we continue to get error reports for Git GUIs we will absolutely revisit the problem.

**Comment by pabloest** [comment]
FYI I tried using VS Code’s built-in Git commit function. VS Code shows me this notification:
<img width="568" alt="Screen Shot 2019-12-18 at 1 20 28 PM" src="https://user-images.githubusercontent.com/302941/71124764-687e2880-219a-11ea-9be4-7c223f0eb117.png">

When I click on the button to open the log, I see some output in VS Code’s “problems” panel, like:
<img width="629" alt="Screen Shot 2019-12-18 at 1 20 50 PM" src="https://user-images.githubusercontent.com/302941/71124804-8055ac80-219a-11ea-9cdd-431306f3fdbe.png">

However, in this case the commit action doesn’t actually complete (the staged files remained staged).

At other times, when I commit using the same procedure, VS Code does not show that notification, the commit succeeds, but I am not shown or prompted to go find any of Bento’s output.
