### ISSUE TITLE
Notify that bento check skips untracked files

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#233]
As of 0.8, `bento check` only runs on files that are tracked by git. For example, running bento after creating a new file with a bug leads to the following:

```
$ bento check
Running Bento checks...

bandit․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․|■■■■■■■■■■| 00:00, 🍱 Done
flake8․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․|■■■■■■■■■■| 00:00, 🍱 Done
r2c.click․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․|■■■■■■■■■■| 00:00, 🍱 Done
r2c.flask․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․|■■■■■■■■■■| 00:00, 🍱 Done
r2c.requests․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․|■■■■■■■■■■| 00:00, 🍱 Done
shellcheck․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․|■■■■■■■■■■| 00:00, 🍱 Done

✔ 0 findings in 2.03 s
$ git status
On branch test
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	new_file.py # <--- file with a bug 

no changes added to commit (use "git add" and/or "git commit -a")
```

I would personally expect check without flags to run on the bare filesystem, so I'd expect the following to return findings before I stage my new file. Bento should either:
1. run on all files on the filesystem, consistent with the behavior of any other linter out there, or
2. let me know that it's only running on files tracked by git, e.g. by saying:
`Note: By default Bento only runs on files tracked by git. Untracked files are ignored.`

**Comment by dlukeomalley** [comment]
This is partially addressed in 0.8.0b10. Let's use #225 for future feature work.
