### ISSUE TITLE
Bento init fails when the Python binary is named python3

### ISSUE THREAD

**Issue by logandk** [returntocorp/bento#237]
## Overview
On a clean Ubuntu 18.10 system with both Python 2 and 3 installed, and with pipenv installed under Python 3, I want to run bento on a simple Flask application. The application uses `pipenv` for installing dependencies and is started using the `python3` binary on the system. I expect bento to run all of its default checks after doing `bento init`.

## Current Behavior

The `bento init` command fails with:

```
✘ Error while running r2c.flake8: Command '.                                          
'/path/to/project/.bento/flake8/bin/activate'; python -m pip install -q flake8~=3.7.0                
flake8-json~=19.8.0 flake8-bugbear~=19.8.0 flake8-debugger~=3.2.0
flake8-executable~=2.0.3' returned non-zero exit status 1.
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Could not find a version that satisfies the requirement flake8-bugbear~=19.8.0 (from versions: 16.4.0, 16.4.2, 16.6.0, 16.6.1, 16.7.0, 16.7.1, 16.9.0, 16.10.0, 16.10.1, 16.11.0, 16.11.1, 16.12.0, 16.12.1, 16.12.2, 17.2.0, 17.3.0, 17.4.0, 17.12.0)
ERROR: No matching distribution found for flake8-bugbear~=19.8.0
```

It appears that bento attempts to run `python` instead of `python3`. I'm assuming the `flake8-bugbear` package doesn't have the required version available for Python 2, causing it to fail. I could not find a way to tell bento to use another Python binary.

## Steps to Reproduce

1. Install Ubuntu 18.10
2. Install both Python 2 and 3 through `apt`
3. Install pipenv using Python 3's `pip3` command
4. Go to the directory of a simple flask application
5. Install dependencies using `pipenv install`
6. Run `bento init` on the application, which is implemented in Python 3 and started with the `python3` binary.

## Possible Solution

Making the path to the Python binary configurable would fix the issue.

## Additional Context
Bento version (run `bento --version`): 0.7.0
Operation system (e.g. Ubuntu 18.04): Ubuntu 18.10
Any other context that would help us reproduce or understand the issue:

**Comment by dmontagu** [comment]
From [PEP394](https://www.python.org/dev/peps/pep-0394/):
> We expect Unix-like software distributions (including systems like macOS and Cygwin) to install the python2 command into the default path whenever a version of the Python 2 interpreter is installed, and the same for python3 and the Python 3 interpreter.

My understanding is that activating an environment amounts to adding a `bin` directory at the start of the path, so that if a python 3 environment is activated, `python3` and `python` will be the same.

From the bento README.md:
> Bento requires Python 3.6+

Given that, maybe it makes sense for bento to just call `python3` rather than `python`?

**Comment by dlukeomalley** [comment]
@logandk Thank you very much for the detailed ticket. @ulziibay and I will debug first-thing tomorrow morning and get started on a fix.

**Comment by ulziibay** [comment]
Please triage to oncall who is Grayson this werk. Also feel free to check
on Pagerduty if you have not installed it yet!

**Comment by dlukeomalley** [comment]
@logank We have a fix that's ready and available in a pre-release: 0.8.0b7.

@brendongo and @ulziibay tracked down the issue to our use of `virtualenv`; tools were defaulting to the version of Python that `virtualenv` was installed with. We fixed the issue by instead running `virtualenv` with the same version of Python used to run Bento.

Can I get your thoughts on the pre-release to confirm the fix? Note that the new version works differently: it runs automatically on diffs as you commit code (fast, focused on your code, catches bugs before CR) and you don’t commit Bento-related files anymore (other project contributors won’t see that you use Bento).

To try it you’ll need Docker installed and can follow these steps:

```bash
$ pip3 install --pre --upgrade --force-reinstall bento-cli
$ cd <PROJECT DIRECTORY>
# Use `git rm` and `git commit` if you previously added Bento files to source control.
$ rm -r .bento*
# Remove the .bento/ ignore pattern from .gitignore, then `bento init`
$ bento init
```

We wrote about the changes in an unlisted [blog post](https://bento.dev/blog/2020/bento-0.8-released-with-updated-workflows-and-new-specialty-checks/) and have an updated [README.md](https://github.com/returntocorp/bento/blob/release/0.8/README.md).

**Comment by LoganK** [comment]
Looks like you tagged in the wrong person. 😛 

@logandk

**Comment by logandk** [comment]
Thanks, I just checked the pre-release and it works!

**Comment by dlukeomalley** [comment]
Thank you all for the contributions! Closing as `fixed`.
