### ISSUE TITLE
Bento shows Bandit B307 using ID instead of human-readable description

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#251]
## Overview
I ran `bento check --all` on the [Flask project](git@github.com:pallets/flask.git) and Bandit reported some results. Most used the newer, human-readable description (e.g., “bandit try-except-pass”) but the eval check was shown as “bandit B307”:
<img width="1280" alt="Screen Shot 2020-01-23 at 5 37 02 PM" src="https://user-images.githubusercontent.com/302941/73038359-ffc44480-3e06-11ea-9c86-1e511bfcddfd.png">

Reference: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b307-eval

## Additional Context
Bento version (run `bento --version`): bento/0.8.0b10
Operation system (e.g. Ubuntu 18.04): macOS 10.15.2

**Comment by dlukeomalley** [comment]
@pabloest @minusworld Agreed with the bug and would like to ship the fix in an 0.8.1 followup. Thoughts?

**Comment by minusworld** [comment]
I'll take care of it! 👍

**Comment by pabloest** [comment]
@dlukeomalley agreed.
@minusworld thanks!
