### ISSUE TITLE
Add Go support

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#26]
We've had a few early users request support for Go, specifically golangci-lint. I'm creating this issue as a general discussion thread.

**Comment by dlukeomalley** [comment]
Consider https://github.com/golangci/govet

**Comment by dlukeomalley** [comment]
Consider https://github.com/securego/gosec

**Comment by minusworld** [comment]
I started on a `gosec` analyzer a few weeks ago.  Here it is for reference: https://github.com/returntocorp/echelon-backend/pull/4094

**Comment by nbrahms** [comment]
This will be released in 0.11
