### ISSUE TITLE
check makefiles

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#267]
**Is your feature request related to a problem? Please describe.**
Makefiles are horrible and have all sorts of hidden whitespace issues. If we had a validatoor for makefiles, it would make my and many other's lives better.

**Describe the solution you'd like**
`bento enable r2c.makefile`
**makefiles are magically checked**

**Comment by dlukeomalley** [comment]
Love it! Do you think it's ok to fold this into #142?
