### ISSUE TITLE
check spelling and grammar in markdown files

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#268]
**Is your feature request related to a problem? Please describe.**
It would be great check spelling and grammar in markdown files in docs folders, etc.

**Describe the solution you'd like**
bento enable r2c.spellingandgrammar
** bento checks spelling and grammar in markdown files**

**Comment by dlukeomalley** [comment]
Love it. Merging this with #150 

@pabloest has been using a "grammar linter" locally that was tedious to setup that's a good candidate for us to use.
