### ISSUE TITLE
bento should detect nested node projects

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#27]
I'm filing this as a bug because the behavior was surprising / unexpected by our reporting user. They have a monorepo with Python and JavaScript split between different directories (i.e. their package.json isn't in their root dir, where they ran `bento init` from).

> I wasn't a fan that it added a `package-lock.json` and another `node_modules` folder to the root directory. We could init bento on each directory individually, but we'd rather run things from the root once.

**Comment by nbrahms** [comment]
Hi @dlukeomalley ... I'm going to remove the bug label here, as we didn't expect the tool to do this as designed. Still a reasonable feature request though. Thanks for your feedback!

**Comment by dlukeomalley** [comment]
@nbrahms Is this addressed by https://github.com/returntocorp/bento-core/pull/175? 👍

**Comment by dlukeomalley** [comment]
I ran into this today during an install session. JS code was in a `web/` subdirectory, and there was no top-level `package.json`

**Comment by dlukeomalley** [comment]
Closing for now as we've deprioritized `eslint`.
