### ISSUE TITLE
GitHub Action succeeds but tools weren't found

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#281]
## Overview
`dlint` could not be found during `bento check --all`, but `check` succeeded. I'm not sure if this is Bento's behavior or the GitHub Action behavior. I expected the tool to fail in this case.

## Current Behavior
https://github.com/returntocorp/bento-core/pull/728/checks?check_run_id=454100396

![image](https://user-images.githubusercontent.com/605906/74796750-5a25b900-527e-11ea-8d2c-d5cb2d8686f6.png)

## Possible Solution
If a configured tool can't be found I think we should error out; its presence in the user's configuration leads me to think that the user expected it to be found and run. The next step (for an error message) could suggest that the user update their configuration file (by removing the tool) OR confirm that the tool is available with the version of Bento they have installed.

## Additional Context
Bento version (run `bento --version`): bento/0.8.2

**Comment by underyx** [comment]
Agreed, this should be a failure. I think bento-cli might be what we need to change here. It seems to me that it exited with exit code 0 even though it knew it was missing a tool. Gimme a green light and I'll make bento-cli exit with another code (after running all checks) if any check couldn't run.

**Comment by dlukeomalley** [comment]
I'm supportive. Let's have Bento fail if a configured *tool* (rather than a check) can't be found. Happy to workshop error messages with you, just looking for it to indicate a clear next step so that a user can get themselves unstuck. Thanks Bence! We'll ship this with 0.10.

**Comment by nbrahms** [comment]
:wave: This should be fixed in 0.10
