### ISSUE TITLE
GitHub Action isn't running latest Bento

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#282]
## Overview
The GitHub Action is not running the latest Bento. I think it's fine for it to lag the formal release by a few days, though I'm not sure the internal process for ensuring the Action is updated consistently.

I noticed this when I saw upgrade notices in the Action's output:

![image](https://user-images.githubusercontent.com/605906/74797100-344ce400-527f-11ea-9907-2879b119c328.png)

See https://github.com/returntocorp/bento-core/pull/728/checks?check_run_id=454100396

## Possible Solution
Add updating the GitHub Action to the release process. CC @underyx @nbrahms @brendongo

**Comment by underyx** [comment]
Right, I forgot to open a discussion about this.

* I've updated the current release now
* I've added instructions in the contributing guide for upgrading

But this is not enough to close this issue. I'd love to amend the release process, but where do I find the existing documentation for it?

**Comment by underyx** [comment]
@dlukeomalley could you point me to some release process docs?

**Comment by underyx** [comment]
Started discussion at https://quip.com/3K3gAxDYZIy6/Using-the-bento-core-repo in a comment.

**Comment by underyx** [comment]
@nbrahms @brendongo as you've authored the process, could I ask you to review the discussion in `Using-the-bento-core-repo`?

**Comment by nbrahms** [comment]
This appears to be complete, so closing as fixed :)
