### ISSUE TITLE
GitHub Action fails when commit is not a merge

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#283]
## Overview
I created a PR on the bento-web repo and this triggered the Action to run. The Action failed at the “Bento checks” step with the message:
```
error: mainline was specified but commit 038f249220696753aa8c11d46160abcd15450212 is not a merge.
fatal: revert failed
```

Here is the check run: [https://github.com/returntocorp/bento-web/pull/30/checks?check_run_id=455958891](https://github.com/returntocorp/bento-web/pull/30/checks?check_run_id=455958891)

Screenshot:
<img width="1096" alt="Screen Shot 2020-02-19 at 10 37 18 AM" src="https://user-images.githubusercontent.com/302941/74864115-da423200-5303-11ea-8d6a-7ff5a2a5d12c.png">

/cc: @underyx

**Comment by underyx** [comment]
Thanks for this report. I'm currently very confused about this, because it seems to me that GitHub guarantees the commit to be a merge commit when running in this mode: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request

Investigating.

**Comment by underyx** [comment]
There's a difference in the checkout step between your repo and working ones:

### Output from https://github.com/returntocorp/ocaml-tree-sitter/runs/459323340

```
git checkout --progress --force refs/remotes/pull/25/merge
Note: switching to 'refs/remotes/pull/25/merge'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.
```

### Output from https://github.com/returntocorp/bento-web/pull/30/checks?check_run_id=455958891

```
git checkout --progress --force 038f249220696753aa8c11d46160abcd15450212
Note: switching to '038f249220696753aa8c11d46160abcd15450212'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.
```

**Comment by underyx** [comment]
@pabloest are you ever of any special branch or PR or merge configuration in bento-web? The step differs only in bento-web, other private repos such as bento-core work correctly, so it's not about the project visibility, either.

**Comment by pabloest** [comment]
@underyx I’m not sure if there’s anything special. My general workflow is to make a new branch based off master, make changes and commits, and then when finished open a PR against master. Then the PR is closed by creating a merge commit into master (not by squashing-and-merging or rebasing-and-merging). Would it be helpful to share what’s in my local `.git` directory?

**Comment by underyx** [comment]
Sadly I don't think so :/ your local `.git` should not affect what's going on on GitHub. What you describe also sounds like the most standard, basic way of running the action, I think it's succeeding for others in the exact same way. Let me try and have a closer look.

**Comment by pabloest** [comment]
Hey @underyx, were you able to find anything here?

**Comment by underyx** [comment]
Heya, sadly, no. I'll have another look _riiiiiight_ now.

**Comment by underyx** [comment]
So. It works on bento-web now; there were some unrelated issues that were breaking the action on that repo.

I figured out what causes the original issue, too. GitHub Actions provides info on the base branch of a PR, but _only_ if it's the first run of the action, and not a re-run.

Re-runs only happen if someone manually triggers one here:

<img width="324" alt="Screenshot 2020-02-26 at 22 11 39" src="https://user-images.githubusercontent.com/1060436/75388277-fab25380-58e4-11ea-88e8-89d8313480a9.png">

This would normally happen only when the action in question has transient failures / flaky tests. @dlukeomalley how would you feel about _not_ fixing that for 0.10 after all and removing the rest of this issue from the project?

**Comment by dlukeomalley** [comment]
I'm fine with that for now, thanks for asking @underyx. Mind filing a ticket so we can track it for a future sprint?

**Comment by underyx** [comment]
Yep @dlukeomalley, filed at https://github.com/returntocorp/bento/issues/291. Closing this as bento-web's action is working now.

**Comment by pabloest** [comment]
Thanks, @underyx !
