### ISSUE TITLE
Explicitly state what "certain browsers" are in meta-charset and meta-content-type explanations

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#286]

**Comment by minusworld** [comment]
cf. https://security.stackexchange.com/questions/47489/utf-7-xss-attacks-in-modern-browsers
cf. https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet#UTF-7_encoding

tl;dr:  "Old versions of Internet Explorer and Netscape"

**Comment by mschwager** [comment]
From a Slack discussion with @minusworld and I:

> I'd expect pushback from small-time shops that only support the latest version of Chrome, but in larger enterprise environments it's more important to consider these kinds of checks

> A lot of the types of bugs these measures prevent live on the fringes of old browsers and unknown/unspecified behavior. If it's a contentious check we should probably just disable it

**Comment by minusworld** [comment]
Will disable meta-charset and meta-contenttype
