### ISSUE TITLE
Update r2c.jinja href message to discuss Jinja's lack of auto escaping

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#288]

**Comment by minusworld** [comment]
Updated in https://github.com/returntocorp/jinjalint/pull/7

**Comment by minusworld** [comment]
Addressed in https://github.com/returntocorp/bento-core/pull/753

**Comment by nbrahms** [comment]
This is the message as printed today:

> The 'href' attribute in anchor tags accepts the 'javascript:' URIand is
       therefore susceptible to XSS even if HTML escaping is enabled.Use
       'url_for' instead of a template variable to generate links.

IMO this addresses the raised issue :)
