### ISSUE TITLE
JavaScript not detected in mixed Python / JS project

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#29]
Running `bento init` on https://github.com/microsoft/project-python-django-webapp only installed Python related tools. I expected it to install both Python and JavaScript tools.

>$bento init
> ...
>Detected project with Python
> 
> ✔ Python package bandit will be installed
> ✔ Python package flake8 will be installed
> ✔ Python package flake8-json will be installed
> ...

Looking at the GitHub language breakdown:

![image](https://user-images.githubusercontent.com/605906/66173054-2580d000-e603-11e9-8ac3-571b7862457f.png)

Bento version: `bento/0.1.0b6`

**Comment by dlukeomalley** [comment]
Users in https://github.com/returntocorp/bento/issues/27 would likely also hit this issue.

**Comment by nbrahms** [comment]
Does the project use node?

**Comment by dlukeomalley** [comment]
Closing in favor of #68.
