### ISSUE TITLE
Bento Action fails on PR check re-runs

### ISSUE THREAD

**Issue by underyx** [returntocorp/bento#291]
## Overview

GItHub acts weird and doesn't give us the base branch as a merge commit parent if an action run is being retried. This is probably a bug. See https://github.com/returntocorp/bento/issues/283#issuecomment-591648702

## Current Behavior

If you retry a job, you'll see something like:

```
error: mainline was specified but commit 038f249220696753aa8c11d46160abcd15450212 is not a merge.
fatal: revert failed
```

## Steps to Reproduce

1. Trigger a failed bento action run
2. Press re-run

## Possible Solution

Ask github support if this is a bug. If they won't fix it, maybe find an alternative way to get the base and head?

**Comment by nbrahms** [comment]
Can we use the `github.base_ref` context variable?

**Comment by nbrahms** [comment]
See https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#github-context
