### ISSUE TITLE
`bento check` summary doesn't appear after exiting pager (i.e. less)

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#30]
After running `bento check` on a project with a large number of findings (triggering Bento's paging logic), if you quit via `q` immediately (without scrolling), no summary information is shown.

![image](https://user-images.githubusercontent.com/605906/66173388-d045be00-e604-11e9-874a-6168ea204462.png)

![Oct-03-2019 17-40-56](https://user-images.githubusercontent.com/605906/66173427-04b97a00-e605-11e9-8ebd-c5940917cd96.gif)

Bento Version: bento/0.1.0b6
Project: https://github.com/facebook/create-react-app e51ea13

**Comment by nbrahms** [comment]
This is fixed in 0.1.0r1
