### ISSUE TITLE
r2c.registry.latest's docker volume mounting doesn't work with the remote Docker daemon of GitHub Actions

### ISSUE THREAD

**Issue by underyx** [returntocorp/bento#309]
## Overview

sgrep currently fails to run in GitHub Actions: https://github.com/returntocorp/bento-action/runs/534590866

## Current Behavior

Bento tries to mount the source directory it's analyzing into the sgrep container. The poor thing has no idea that sometimes the Docker daemon is remote though, so the path it finds source at is actually not what needs to go in a `docker run -v src:dst` command as `src`.

## Steps to Reproduce

See commands that triggered https://github.com/returntocorp/bento-action/runs/534590866

## Possible Solution

What we agreed on on a call with @ievans, @dlukeomalley, and @nbrahms is that instead of assuming the `src` path should be the current working directory, using the path from the `GITHUB_WORKSPACE` env var if we're in GItHub Actions.

## Additional Context

Bento version (run `bento --version`): 0.10.1

**Comment by underyx** [comment]
@dlukeomalley @nbrahms I actually don't remember, did we reject the proposal that goes like:

1. `docker run … sleep infinity`
2. `docker cp src sgrep-container:/src`
3. `docker exec sgrep-container sgrep`

?

This is not much more work, and has the benefits of fixing this issue for anyone running bento with a remote docker daemon (for example Docker for Mac users that don't have their code directory already mounted in their Linux VM) and this way we can avoid bento-core having special cases for GitHub Actions.

**Comment by nbrahms** [comment]
IIRC `docker cp` would cause performance issues for development-workflow.

Also, you can just `docker start` instead of `docker run sleep infinity`.

**Comment by nbrahms** [comment]
cc. @brendongo for visibility

**Comment by underyx** [comment]
Well, shellcheck uses a third one where we invoke a process one by one in the container and pipe via stdin. My hunch was that `docker cp N + 1 sgrep invoke` would be faster than `N sgrep invokes with files piped in one by one`.

But recall, the alternative is to keep everything as it was and just hack GHA. I personally would just try both ways actually and see which is faster.

**Comment by nbrahms** [comment]
Can we just do the `cp` only inside the GHA?

FWIW, in analyzers we use an environment variable `R2C_USE_REMOTE_DOCKER`
to control. If we use this, we could just `docker cp` in that case, and set
that on the GHA.
