### ISSUE TITLE
Reduce Bento Action setup time

### ISSUE THREAD

**Issue by aexvir** [returntocorp/bento#311]
Right now the whole GitHub action is taking a minute and a half for a 6s analysis, which is totally suboptimal.

Instead of building every time the complete docker image from scratch it would be much better to distribute `bento` as a docker image, with just the cli installed, and having this action just copying the small shell script inside.

That `bento` image can then be versioned, and distributed openly, so people using GitLab CI for example can use it 🙂

**Comment by dlukeomalley** [comment]
Transferring this issue from /bento-action to /bento for easier ticket tracking on my end.

**Comment by aexvir** [comment]
> What were the circumstances that led you to investigate and notice this issue?
Well... when I added it, and saw that it was taking like three times more than [`coala`](https://github.com/coala/coala), which is a tool that more or less does the same, and it's known for its slow performance, I was just surprised.

Even if it takes less than other jobs, in environments where CI time is limited in minutes you don't really want to waste time. And even in self-hosted environments like ours, we don't want to lock a shared runner for 1min 30s if the job takes only 6s.

> I love this idea. If we shipped a GitLab friendly docker-image would you adopt it in your build process?
If it proves to be useful that's the idea. So far we are still getting really good results with `pre-commit` and our own set of tools there

Regarding #302 , yep, that's nice. We already have that output from tools like SonarQube for example 🙂

**Comment by dlukeomalley** [comment]
> And even in self-hosted environments like ours, we don't want to lock a shared runner for 1min 30s if the job takes only 6s.

What is an acceptable setup time? I agree 1min 30s is way too long. Is 30s the right threshold, 10s, something else?

> If it proves to be useful that's the idea.

Haha, I can follow-up privately. I want to know what would help it prove useful to you 🙂

**Comment by dlukeomalley** [comment]
@aexvir The Bento Action now uses a Bento docker image. Download and setup time are down by 1-2 minutes.

No action on your end to get these improvements! Your next PR that Bento runs on will use the updated Action.

**Comment by aexvir** [comment]
I couldn't confirm the fix so far as we haven't really made development in the project using it, but I can confirm it now 🙂

**Comment by dlukeomalley** [comment]
Keep us posted @aexvir. We've also got a docker image / GitLab integration in the works.

**Comment by aexvir** [comment]
Oops, sorry if I wasn't clear enough. I can confirm that it's much better now. It finishes in around 30s, where 10s it's spent pulling the image. I guess the image could be a bit smaller, but is not a big deal.

> We've also got a docker image / GitLab integration in the works.
Is there an issue I can follow?
