### ISSUE TITLE
`bento` does not see `jwt_required` in class attribute decorators

### ISSUE THREAD

**Issue by valeriykundas** [returntocorp/bento#316]
## Overview
bento does not see `jwt_required` in class attribute `decorators`. works fine with `@jwt_required`

```
from flask import Flask
from flask.views import MethodView
from flask_jwt_extended import jwt_required

app = Flask(__name__)

class UserAPI(MethodView):
    decorators = [jwt_required] # does not see there

    # @jwt_required #  uncommented works fine
    def get(self, user_id):
        pass

app.add_url_rule("/", view_func=UserAPI.as_view("/users"))
```

## Current Behavior
```
r2c.flask missing-jwt-token https://checks.bento.dev/en/latest/flake8-flask/missing-jwt-token
     > app.py:13                                                                      
     ╷                                                                                
   13│   def get(self, user_id):                                                      
     ╵                                                                                
     = This file has flask_jwt, flask_jwt_extended, or flask_jwt_simple
       imported, but no authentication protection with @jwt_required or
       @jwt_optional. This means JWT tokens aren't being checked for access to
       your API routes, which may be a security oversight.

⚠ 1 finding(s) due to staged changes in 1.01 s
```

## Steps to Reproduce

1. create `app.py` and paste the code from above.
2. install Flask and flask-jwt-extended
3. run `bento init`
4. git add .
5. run `bento check`

## Additional Context
Bento version: 0.8.0
Operating system: Ubuntu 18.04
Python 3.7

**Comment by dlukeomalley** [comment]
@valeriykundas Thank you for filing a ticket. Tagging @minusworld for his thoughts and help investigating `r2c.flask missing-jwt-token`.

**Comment by minusworld** [comment]
Hi @valeriykundas! Thanks for the report.

Would you be able to link some documentation or a reference about the `decorators` class attribute? I've not seen that pattern before. Is it Flask-specific, or something introduced in a specific version of Python?

In the meantime, you can **archive** the finding using `bento archive`. This will suppress the finding.

Thanks!

**Comment by valeriykundas** [comment]
Hi! Thank you for your reply!

Here are the links to documentation and the source code. As mentioned there it is introduced in Flask 0.8

https://flask.palletsprojects.com/en/1.1.x/views/#decorating-views
https://flask.palletsprojects.com/en/1.1.x/api/#flask.views.View.decorators
https://github.com/pallets/flask/blob/2062d984abd3364557a6dcbd3300cfe3e4ecf156/src/flask/views.py#L56

I changed that to single decorators. But using single decorator would be useful if class has many methods.

Thank you!

**Comment by minusworld** [comment]
Perfect, thank you!

We'll improve the check to detect this soon. 👍

**Comment by minusworld** [comment]
@valeriykundas We just published an update for this! Bento should pick up the patch.  Please re-open the issue if something is amiss.  Thanks! 🙏
