### ISSUE TITLE
Disable bandit's pseudo-random generator warnings

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#32]
> main.py
>  92:0  advice  Standard pseudo-random generators are not suitable for security/cryptographic purposes. r2c.bandit     blacklist
>  93:0  advice  Standard pseudo-random generators are not suitable for security/cryptographic purposes. r2c.bandit     blacklist

In these instances these are innocuous:

> new_count = menu[i] + random.choice([-1, 1])

We've heard from others pseudo-random generator warnings are perceived as noisy.

Bento version: bento/0.1.0b6
Project: private

**Comment by nbrahms** [comment]
@minusworld to triage

**Comment by minusworld** [comment]
It looks like this check, named `random`, is disabled in the default config.  

https://github.com/returntocorp/echelon-backend/blob/develop/src/r2c/bento/bento/configs/default.yml#L15

https://github.com/PyCQA/bandit/blob/master/bandit/blacklists/calls.py#L192

I wonder if the name random isn't correct, or something... ?🤔

**Comment by dlukeomalley** [comment]
@minusworld Any chance #37 is a result of trying to fix this ticket?

**Comment by nbrahms** [comment]
@dlukeomalley @arashd Can you confirm that this is still an issue? I think this was fixed when moving bandit to id-based check identification.

**Comment by dlukeomalley** [comment]
Confirmed working. Thank you!
