### ISSUE TITLE
Suggest `bento archive --all` after `bento check --all`

### ISSUE THREAD

**Issue by rcoh** [returntocorp/bento#322]
**Is your feature request related to a problem? Please describe.**
It's a little confusing because bento says:
```
◦ To archive findings as tech debt, run $ bento archive
```
but then if you do that:
```
0 finding(s) due to staged changes were archived, and will be hidden in future Bento runs.
```
(It will delete your bento archive)

**Describe the solution you’d like**
It should actually say:
```
◦ To archive findings as tech debt, run $ bento archive --all
```

**Comment by dlukeomalley** [comment]
Closing as a duplicated of #252
