### ISSUE TITLE
Out of the box installation fails during newsletter signup

### ISSUE THREAD

**Issue by azuisleet** [returntocorp/bento#332]
## Overview
Running the quick setup command on the home page:
`pip3 install bento-cli && bento init` 
results in an error during registration.

https://github.com/returntocorp/bento/blob/ce11d21d538cd5e75f53fe498c431dfc134c9f57/bento/commands/register.py#L119-L121

## Current Behavior
```
What is your email address? [my@email.address]: 

...
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='waitlist.r2c.dev', port=443): Max retries exceeded with url: /subscribe (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa3d5f80150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

## Steps to Reproduce

1. Start from an uninitialized state
2. `bento init`
3. Enter an email address

## Possible Solution
Unknown

## Additional Context
Bento version (run `bento --version`): bento/0.12.0
Operating system (e.g., Ubuntu 18.04): N/A
Any other context that would help us reproduce or understand the issue: N/A

**Comment by dlukeomalley** [comment]
@azuisleet We've restored functionality and are investigating why our monitoring didn't detect this endpoint being down. Please try `bento init` again and let us know if you run into any future issues.

Thank you very much for filing a ticket!
