### ISSUE TITLE
Always show an archive summary

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#35]
After archiving my project's issues, `bento check` will tell me there are zero issues. In addition to that, I'd love to be reminded of how much tech debt I have, maybe also a summary of categories. Maybe:

```
$ bento check
Running Bento checks...
  r2c.bandit: |███████████████| 00:01, 🍱
  r2c.eslint: |███████████████| 00:01, 🍱
  r2c.flake8: |███████████████| 00:02, 🍱

Keep in mind that you have 19 archived issues!
security: 5     correctness: 12   maintainability: 2

✔ 0 findings in 2.46 s
```

**Comment by dlukeomalley** [comment]
@arashd Because we haven't had activity here for 27 days, I'd like to close this ticket and role it into the work @dan5382 is doing now that involves better sign-posting and tech debt stats.

**Comment by arashd** [comment]
is there an issue tracking that work? I heard a user quote related to this that I wanted to add.

**Comment by dlukeomalley** [comment]
See #146!
