### ISSUE TITLE
Bandit check-ids printed as urls

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#37]
Bandit check-ids showed as URLs, which are long and cumbersome as check-ids.

![image](https://user-images.githubusercontent.com/605906/66281029-47ca5600-e86e-11e9-94c8-1246c10220b0.png)

Running `bento disable` does not disable this rule from displaying in subsequent runs.

Bento version: bento/0.1.0r2

**Comment by nbrahms** [comment]
Hi @dlukeomalley... do you have a clone link I can use to reproduce the issue?

**Comment by dlukeomalley** [comment]
@nbrahms, I just invited you as a collaborator to my private repo with this issue. Let me know what else you need!

**Comment by nbrahms** [comment]
@dlukeomalley This is fixed on 0.1.0r3. Happy coding.
