### ISSUE TITLE
`bento archive` reports the incorrect number of tools

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#38]
Running `bento archive` with two results from `r2c.bandit` reported `Rewrote the whitelist with 2 findings from 2 tools`. In this case it was 2 findings from 1 tool. Is the # of tools based on those producing current findings or all those that have been configured?

![image](https://user-images.githubusercontent.com/605906/66281211-19994600-e86f-11e9-8711-d32efb6056f2.png)

**Comment by nbrahms** [comment]
Hi @dlukeomalley . IMO this is expected behavior. We display the number of configured tools.

**Comment by dlukeomalley** [comment]
In this case, what if we don't mention the number of tools?

```
Rewrote the whitelist with 2 findings.
```

When you say rewrote, will the number of findings reported be the total number of findings (i.e. `--all`) or the number of new findings?

**Comment by nbrahms** [comment]
We've just released 0.1.0r4.

In this new release we display tool run progress, so we've removed the tool counter from the summary.

In addition, we give you a break down of how many findings are new vs. existing.

Please check it out and let me know what you think.

**Comment by dlukeomalley** [comment]
Confirmed working. Thank you @nbrahms!
