### ISSUE TITLE
`bento init` fails, source builtin may not be available in all shells

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#42]
Error:

> ✔ Python package bandit will be installed
> ⚠ Could not execute "s o u r c e   . / . / . b e n t o / b a n d i t / b i n / a c t i v a t e ;   p y t h o n   - m   p i p   i n s t a l l   - q   b a n d i t":
> /bin/sh: 1: source: not found
>     Error [Errno 13] Permission denied while executing command python setup.py egg_info
> Exception:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
>     status = self.run(options, args)
>   File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
>     wb.build(autobuilding=True)
>   File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
>     self.requirement_set.prepare_files(self.finder)
>   File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
>     ignore_dependencies=self.ignore_dependencies))
>   File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 634, in _prepare_file
>     abstract_dist.prep_for_dist()
>   File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 129, in prep_for_dist
>     self.req_to_install.run_egg_info()
>   File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 439, in run_egg_info
>     command_desc='python setup.py egg_info')
>   File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 685, in call_subprocess
>     cwd=cwd, env=env)
>   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
>     raise child_exception
> OSError: [Errno 13] Permission denied

User explaination:

> /bin/sh points to /bin/dash in my machine, and this does not support the 'source' builtin (probably a bash thing). You probably want '.' instead of 'source'.

Bento version: bento/0.1.0r2
Running on ubuntu 18.04

**Comment by aryx** [comment]
I think this is fixed in 0.1.0b5

**Comment by dlukeomalley** [comment]
@nbrahms Was this explicitly addressed in recent releases?

**Comment by nbrahms** [comment]
@dlukeomalley I don't believe so. At this point, having `bash` should be a qualification for running `bento`.

**Comment by nbrahms** [comment]
This is fixed on master.

**Comment by arashd** [comment]
@dlukeomalley can we get in touch with the user here to confirm our fix works for them?

**Comment by dlukeomalley** [comment]
@arashd Let's test and close this out next release (when master -> release). 

The original user was @aryx 😛

**Comment by nbrahms** [comment]
Hi @arashd, @dlukeomalley: I think this confirms the fix:

```
% csh -c "bento check"
Running Bento checks...
  r2c.bandit: |███████████████| 00:01, 🍱
  r2c.eslint: |███████████████| 00:00, 🍱
  r2c.flake8: |███████████████| 00:02, 🍱

✔ 0 findings in 2.27 s
```

**Comment by dlukeomalley** [comment]
Awesome! Closing this one out then. Thanks @nbrahms!
