### ISSUE TITLE
Uninstall bento as a pre-commit hook

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#43]
If we eliminate the need for knowing where git hooks live in the hook installation process, we should also allow users to uninstall the hook if they decide they don't want Bento to run as a pre-commit hook anymore.

**Comment by dlukeomalley** [comment]
I'm closing this issue for now because we haven't had activity on it for 23 days. As we further develop our precommit story, let's revisit it and include an uninstall.

**Comment by dlukeomalley** [comment]
Added to 0.8
