### ISSUE TITLE
Make Bento IDE-ready

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#47]
Let users see Bento output in Emacs/VSCODE/Efuns by providing machine parsable (json?) output.

**Comment by aryx** [comment]
O think @deifactor  has something already for that (she made an emacs mode for bento).

**Comment by aryx** [comment]
I've found: bento check --formatter bento.formatter.Json
which outputs errors in Json. It's available in 0.2.0b1 at least for me.

**Comment by nbrahms** [comment]
Closing this as done. Thanks for the submission @arashd .

**Comment by arashd** [comment]
I think it's not closed for whatever reason. closing.
