### ISSUE TITLE
Inconsistent output when mailing list signup fails

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#49]
When the mailing list subscription process gets started from `bento check`, we still output that:

```
We were unable to subscribe you to the Bento mailing list, but will continue with installation.
```

Followed by 

```
✘ No Bento configuration found. Please run `bento init`.
```

"continue with installation" is confusing wording. Let's change the wording here to work with any command that might trigger the privacy policy review to start.

**Comment by dlukeomalley** [comment]
Spoke with @arashd, will make a small tweak to resolve this issue in 0.3.0 telemetry work!
