### ISSUE TITLE
Show success messaging upon initialization

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#53]
I initialized Bento and see the following messages:
```
$ bento init
Creating default configuration at ./.bento.yml

Detected project with Python

✔ Creating virtual environment for r2c.bandit
✔ Python package bandit will be installed
✔ Creating virtual environment for r2c.flake8
✔ Python package flake8 will be installed
✔ Python package flake8-json will be installed
$
```

I understand these packages will be installed, but I am not sure if the checkmark indicates the packages were successfully installed. Additionally, I am unsure if Bento successfully installed.

**Comment by tnarla** [comment]
What bento init outputs now: 

`~/R2C/bento-core(tru/install-hook*) » bento init                                                              
Creating default configuration at ./.bento.yml

Detected project with Python

✔ Creating virtual environment for r2c.bandit
✔ Python package bandit will be installed
✔ Creating virtual environment for r2c.flake8
✔ Python package flake8 will be installed
✔ Python package flake8-json will be installed`

**Comment by pabloest** [comment]
Thanks, @tnarla ! I accidentally hit a keyboard shortcut shortly after I submitted the issue, so I updated the text just now.

**Comment by dlukeomalley** [comment]
We now display:

> ✔ Bento is initialized on your project.

I'm going to close this issue as resolved for now, and we'll think about further improving this as part of @dan5382 `bento init` redesign work.
