### ISSUE TITLE
Add .bento to gitignore or ask user to do it

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#56]
We should either automatically add `.bento` to `.gitignore` if git is set up, or instruct the user to do it in the message when `bento init` is finished. Otherwise, the user will see hundreds of untracked files they might stage and get very confused.

**Comment by dlukeomalley** [comment]
From a user today:

> So bento leaves a couple of untracked things in my root: .bento-whitelist.yml .bento.yml .bento/
> I wish they got added them to .gitignore if found

**Comment by dmontagu** [comment]
> Otherwise, the user will see hundreds of untracked files they might stage and get very confused.

Precisely what happened to me 😄.

* +1 for adding `.bento/` to `.gitignore` (**with a prompt**).
* I would also suggest printing a message after running `bento init` with a brief description of what the `.bento-whitelist.yml` and `.bento.yml` files *are*.
    * Looking at the `.bento.yml` I can get a sense, but the `.bento-whitelist.yml` is empty so I have no idea.
* I would suggest *not* adding `.bento-whitelist.yml` or `.bento.yml` to the `.gitignore` by default; it seems like these should be version controlled? Certainly if including bento as a CI step or similar.

**Comment by dlukeomalley** [comment]
We've added this as a prompt and automatic feature as of `bento/0.1.0.post1`.

```bash
It looks like you're managing this project with git. We recommend adding '.bento/' to your '.gitignore'.
  Do you want Bento to do this for you? [Y/n]:
✔ Added '.bento/' to your .gitignore. Please commit your .gitignore.
```

Let us know if you'd like to see any other modifications!
