### ISSUE TITLE
Consistently underline hyperlinked text in output

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#63]
It's unclear what text is hyperlinked or clickable in our output. I'd like to standardize on how we output and display this content, perhaps with underlines like is done for check-ids:

![image](https://user-images.githubusercontent.com/605906/66504898-0eb50000-ea7f-11e9-84fe-7b9ba201c881.png)

I'm able to click on both r2c.flake8 and F401. Are both hyperlinked by us?

**Comment by nbrahms** [comment]
Hi @dlukeomalley ,

Only the underlined link is created by us. It's possible that you have a terminal integration allowing clicking on the tool name?

**Comment by dlukeomalley** [comment]
Likely, will close out. Thanks @nbrahms
