### ISSUE TITLE
Long delay when running as commit hook

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/bento#64]
This was discovered when running `bento` as a commit hook on `git@github.com:SortableJS/Vue.Draggable.git`.

### Steps to reproduce:

- Edit a `js` file and stage it for commit.
- Run `git commit`

### Behavior:

- There is a 30 second lag before `bento` emits any output

(Bento running on its own takes 2 seconds total)

### Expectation:

- Sub-second lag

**Comment by dlukeomalley** [comment]
@nbrahms Is this still affecting you?

**Comment by nbrahms** [comment]
@dlukeomalley I just validated that this is no longer an issue when using 0.1.1b3.
