### ISSUE TITLE
Rename .bento-whitelist.yml to .bento-archive.yml

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#67]
This ticket is to connect the command `bento archive` to what it produces, `.bento-whitelist.yml`. I'd like to be consistent in terminology and make it clear where/what causes files to exist. I'm open to alternative names and ideas!

**Comment by nbrahms** [comment]
Hi @dlukeomalley ,

One issue we'll have in such a rename is how to deal with the file during version upgrade. What would be your expectation here? I can think of a couple options:

- `bento` emits a notice on upgrade indicating that the archive file will need to be rewritten
- `v 0.2.0` of `bento` automatically renames the file

Curious to hear your thoughts.

**Comment by dlukeomalley** [comment]
Closing in favor of #121
