### ISSUE TITLE
Support `bento help` and `bento --help`

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#75]
**Is your feature request related to a problem? Please describe.**
I'm used to typing `bento help` the same way `aws help` works.

**Describe the solution you'd like**
`bento help` == `bento --help`

**Comment by pabloest** [comment]
What do you think of outputting the help whenever the users types `bento` + `[unknown command]`?

**Comment by dlukeomalley** [comment]
@pabloest That's the behavior of Bento right now. Digging into this request, the complaint is that typing `bento help` returns the following:

```bash
$ bento help
Usage: bento [OPTIONS] COMMAND [ARGS]...
Try "bento --help" for help.


Error: No such command "help”.
```

The `Error: No such command "help”.` line seemed duplicative to the user:

> This is annoying

**Comment by pabloest** [comment]
@dlukeomalley I agree that the `Error: No such command "help”.` line seemed duplicative to the user.

What I suggest is that when a user types
```console
bento chicken
```
that Bento returns:
```console
Error: No such command "chicken."

Usage: bento [OPTIONS] COMMAND [ARGS]...

Options:
  -v, --verbose  Show extra output, error messages, and exception stack traces
                 with INFO filtering
  --version      Show current version bento.
  --agree        Automatically agree to terms of service.
  --help         Show this message and exit.

Commands:
  archive       Adds all current findings to the whitelist.
  check         Checks for new findings.
  disable       Disables a check.
  enable        Enables a check.
  init          Autodetects and installs tools.
  install-hook  Installs bento as a git pre-commit hook Saves any existing...
```

Perhaps this is a separate issue and I’m happy to open a new one to track

**Comment by dlukeomalley** [comment]
Given the age of this ticket I'm marking it `stale`. The behavior seems consistent with click projects and other CLIs, and I'd like to focus our efforts on larger features (and fewer tickets 😄). Are there any concerns or other details we should consider to reopen this ticket?
