### ISSUE TITLE
Bento should indicate how to fix broken state

### ISSUE THREAD

**Issue by dmontagu** [returntocorp/bento#77]
Make sure you are running the latest version of Bento.

**Describe the bug**
I am getting an error parsing the results of `r2c.bandit` when I run it on [pydantic](https://github.com/samuelcolvin/pydantic)

**Expected result**
No error

**Actual result**
```
> bento --verbose check
Running Bento checks...
  r2c.bandit: |███            | 00:00, 🍤Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bento/tool.py", line 160, in results
    violations = self.parser().parse(raw)
  File "/usr/local/lib/python3.7/site-packages/bento/extra/bandit.py", line 133, in parse
    results: Dict[str, List[Dict[str, Any]]] = json.loads(input)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bento/cli.py", line 184, in __tool_filter
    tool.tool_id, __tool_findings(tool, config, paths), baseline
  File "/usr/local/lib/python3.7/site-packages/bento/cli.py", line 140, in __tool_findings
    return tool.results(tool_config, paths)
  File "/usr/local/lib/python3.7/site-packages/bento/tool.py", line 162, in results
    raise Exception(f"Could not parse output of '{self.tool_id}':\n{raw}")
Exception: Could not parse output of 'r2c.bandit':
```

**Additional context**
os: MacOS 10.14.6
python: 3.7.3
bento: 0.1.0
project: [pydantic](https://github.com/samuelcolvin/pydantic) master branch (commit 46db1ef)

**Comment by dmontagu** [comment]
Looks like the output is empty, and json.loads() doesn't like that. I don't know if empty output should be expected, or if there is an upstream issue.

**Comment by pabloest** [comment]
Thanks for filing this issue, @dmontagu. Do you use pydantic regularly or is there a particular reason you ran Bento on pydantic?

**Comment by dmontagu** [comment]
It's one of the libraries I contribute to most.

I didn't have any issues come up on the first project of mine that I tried bento on, so I wanted to try on another project, and ran into this issue. I also figured it might be useful to try it out on a public repository for the sake of reproducibility by the devs 😄.

**Comment by pabloest** [comment]
Got it. Thanks for the clarification! We appreciate that you ran Bento on several projects. We’ll look into the issue and track it here.

**Comment by nbrahms** [comment]
Hi @dmontagu 

I've been trying to reproduce this and having some trouble. My current hypothesis is that bandit is possibly crawling some untracked directory or file that isn't on the clean checkout.

If possible, could you send me the output of `git status --ignored` for your checkout of pydantic?

For posterity, here's what my run of bento looked like on the same commit hash as you posted (this is on Mac Mojave 10.14.5 and Python 3.7.4; I'm assuming the subminor versions don't affect things... hopefully):

```
➜  pydantic git:(46db1ef) ✗ bento check
Running Bento checks...
  r2c.bandit: |███████████████| 00:06, 🍱
  r2c.flake8: |███████████████| 00:02, 🍱

docs/examples/constrained_types.py
 66:1  error   undefined name 'debug'                                                                               r2c.flake8     F821

docs/examples/ex_post_init_post_parse.py
  1:1  error   'datetime.datetime' imported but unused                                                              r2c.flake8     F401

docs/examples/ex_secret_types.py
  1:1  error   'typing.List' imported but unused                                                                    r2c.flake8     F401

docs/examples/example2.py
  4:5  error   undefined name 'User'                                                                                r2c.flake8     F821

docs/examples/export_pickle.py
 16:0  warning Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible s... r2c.bandit     B301

docs/examples/postponed_broken.py
  6:5  error   expected 1 blank line before a nested definition, found 0                                            r2c.flake8     E306

pydantic/parse.py
 42:0  warning Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible s... r2c.bandit     B301

pydantic/utils.py
 79:0  warning Use of possibly insecure function - consider using safer ast.literal_eval.                           r2c.bandit     B307

tests/test_construction.py
191:0  warning Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible s... r2c.bandit     B301
203:0  warning Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible s... r2c.bandit     B301
231:0  warning Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible s... r2c.bandit     B301

tests/test_validators.py
646:0  warning Use of exec detected.                                                                                r2c.bandit     B102

⚠ 12 findings in 6.67 s

To suppress all findings run `bento archive`.
```

**Comment by nbrahms** [comment]
@dmontagu Another thing to try would be to `rm -rf .bento` in your project root, and run `bento check` again. If that makes a difference it would imply an instability in our code that we need to fix.

**Comment by dmontagu** [comment]
@nbrahms Yeah, the rm -rf .bento thing fixed it. Sorry I can't offer more information about why!

**Comment by dlukeomalley** [comment]
Let's close this out for now everyone. Thanks for the back and forth and glad it's fixed now.

**Comment by dmontagu** [comment]
I ran into this again after updating to 0.3.0, and had to re-run the `rm -rf .bento`. I didn't remember exactly how I had fixed this before, so I ended up wasting several minutes trying to recall what to do before searching for this issue and repeating the steps.

Might be worth adding a note about this in the output if the tools exit with errors?

**Comment by nbrahms** [comment]
Hi @dmontagu,

Thanks for the report! We have a ticket for this, and I'll look at revising
its prioritization.

**Comment by dlukeomalley** [comment]
@nbrahms I'm going to re-open this for tracking purposes. Mind linking the new ticket when you can?

**Comment by nbrahms** [comment]
@dlukeomalley Sure thing. I'll link from our internal ticket. Also moving from bug to enhancement.

**Comment by nbrahms** [comment]
@dmontagu @dlukeomalley Here's the UI I'm playing with now (I purposely corrupted the installation):

![image](https://user-images.githubusercontent.com/2490631/68353627-0a502700-00bf-11ea-8d96-304146446584.png)

Whatcha all think?

**Comment by dmontagu** [comment]
I think the `bento init --clean` suggestion is great.

It would be nice if there was a way to get it to show a more complete error output (e.g., in my case, the full stack trace from the failed call to bandit); it's not clear to me if the new approach achieves that or not. But if `bento init --clean` fixes it in all known cases then I think that's enough!

**Comment by nbrahms** [comment]
Hi @dmontagu . We do wrestle a bit with how much to spam your screen with tracebacks, as there are tradeoffs for readability and debugging completeness. Currently we log the stack trace in you `~/.bento/last.log`, but hide the trace on your screen.

I wonder if a simple "to see the complete stack trace, see ~/.bento/last.log" message would complete the workflow?

**Comment by dmontagu** [comment]
Yep that would be good. Mostly so I can do basic debugging myself easily.

**Comment by dlukeomalley** [comment]
This is shipping in 0.4!
