### ISSUE TITLE
Feature request: .bentoignore

### ISSUE THREAD

**Issue by dmontagu** [returntocorp/bento#78]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to exclude some files from analysis.

For example, running over [pydantic](https://github.com/samuelcolvin/pydantic), a handful of issues are flagged in the docs examples (which are .py files), but that is because not all docs examples are self-contained. These files are excluded from linting in the existing CI jobs.

I recognize that I could just use `bento archive` to ignore those issues, but I'd like to 1) preempt any issues being flagged in those files in the future, and 2) avoid wasting time analyzing those files on every run.

**Describe the solution you'd like**
Something analogous to .gitignore.

**Comment by pabloest** [comment]
We really appreciate the thoughtful feedback, @dmontagu, and for documenting and labeling the issue here.
