### ISSUE TITLE
Use global Bento env in ~/.bento instead of per-project Bento env

### ISSUE THREAD

**Issue by dmontagu** [returntocorp/bento#79]
**Is your feature request related to a problem? Please describe.**
It looks like every time I run `bento init` on a new project, it creates 33MB worth of virtual environments for flake8 and bandit.

It's not the end of the world, but if I were to install this locally for all of my python projects it would add up to a lot of wasted space.

------

As far as I can tell, the environments don't *need* to be repeated for each project; the environments are isolated from the project environment anyway. Maybe it needs to respect the python version, but even in that case, it seems to me that it would be fine to have one environment per python version living inside of `$HOME/.bento`.

(But I could totally be overlooking a good reason to repeat the environment creation for each project.)

**Describe the solution you'd like**
A more global installation of the flake8 and bandit environments, e.g. in `$HOME/.bento/environments/python3.X/<flake8|bandit>`, or similar.

**Comment by dmontagu** [comment]
Might be worth looking into the way [`poetry`](https://github.com/sdispater/poetry) vendors its dependencies when installed via the [`get-poetry.py`](https://github.com/sdispater/poetry/blob/master/get-poetry.py) install script. That's pretty close to the ideal implementation for me.

I recognize there may be fundamental incompatibilities between having a global installation and using `pip install` to install the tool, and I see the benefits that come with such an easy installation. But if I were using this in all my projects I would much prefer a global installation, similar to what poetry does.

-----

Admittedly, this is not how many other linting/related tools like black, isort, etc., work. But I think that is because those tools *need* to be installed in the same environment so they can inspect the environment (e.g., to see which packages are installed). I would understand if that were eventually necessary, so having global environments was unnecessary, but I would think that in that case you'd probably be able to get rid of the isolated environments anyway.

**Comment by pabloest** [comment]
Appreciate the insight here, @dmontagu. We’ve heard positive things about `poetry` and will take a closer look. As you mention, there are a few things to balance here including compatibility, ease of installation, efficiency, and more. We’ll look into this and update here as we have info.

**Comment by dmontagu** [comment]
@pabloest 

Maybe I'm using a "bad" workflow: should I be installing bento-cli separately into each of my virtual environments? Or would it work if I just installed bento-cli into a non-virtual-environment and relied on the shell looking higher up the path to find bento-cli?

I bring this up because I ran into a problem where pip-installing bento-cli changed the version of one of my project dependencies (attrs), which led to some brief confusion.

**Comment by dlukeomalley** [comment]
Another angle to consider is whether we should use a project's `package.json` and npm vs. yarn. See https://github.com/returntocorp/bento/issues/81#issuecomment-541213959

**Comment by dmontagu** [comment]
Yeah, a relatively simple short-ish-term workaround might involve a basic search for requirements (via setup.py/setup.cfg/requirements.txt/pyproject.toml/etc.) and just printing a warning if any detected requirements conflict with bento. (I would mind less if my environment got modified if bento warned me.)

Long term though it should probably support installation in a way that always avoids conflicts with the dev environment.

**Comment by arashd** [comment]
@dmontagu your suggestion of using a single installation of each tool (for each python version) should do the trick. @nbrahms were there downsides to having global installs that made us want to avoid it?

**Comment by dmontagu** [comment]
@arashd have you thought about the impact moving to global environments would have on integrating with the development environment? It seems to me like it might be (eventually) useful for bento to be able to inspect dependency code when assessing your code base.

I presume you could do things like modify the python path to detect the site-packages (carefully, so as not to break bento's own requirements) even if running in a separate environment. But I don't know how hard that would be in practice, and given this seems like a natural evolution, probably worth thinking about hard now.

**Comment by deifactor** [comment]
FWIW one downside of global installs (which is why I pushed against it) was that it means that *all* your projects will be running the same version of flake8 and such. So if one project wants a new version for some shiny feature, but another project can't use that new version, you're stuck. Similar to the reason people use virtualenvs in the first place as opposed to just installing everything into the user's site-packages.

**Comment by dmontagu** [comment]
@deifactor But you wouldn't be using that version of flake8 in *your project*, and it wouldn't be a part of the development environment, it would just be *bento* using it.

If the "global environment" approach is compatible with bento, the "global environment" bento uses should probably still be a virtualenvironment, just one that the bento cli knows to look for, in a standard location (e.g., ~/.bento/venvs/`).

The only risk then would be if you need *bento* to use a different version of flake8 with one project versus another. This seems like it would be exceedingly rare (but let me know if I'm overlooking something).

**Comment by arashd** [comment]
The way I (and I imagine most users) have been using Bento, is by installing it on my system python (to be more specific, not the MacOS default one, but the `brew` installed one), so it's not technically in a virtualenv, which means it's on my path even if I've activated a virtualenv that I've created for a project I'm working on. In that framing, there are three python envs at play:
- the _system_ brew python3 env where Bento is installed
- one for bandit in the `.bento/` dir
- one for flake8 in the `.bento/` dir
- one for the project I'm checking in say `~/.venvs`

Technically, even now, our project and bento tools aren't sharing an environment. 

If I'm understanding this issue correctly, @dmontagu is advocating for moving the stuff in `<project-dir>/.bento` to `~/.bento/venvs`. Is that a fair representation? To address @deifactor's concern, we could create separate venvs in `~/.bento/venvs` each time we init on a new project.

**Comment by dmontagu** [comment]
@arashd Thanks for clarifying!

I was installing it into my virtual environments (I think the 4th category in @arashd's list) for two reasons:

1. That's what is active when I open PyCharm and run `pip3 install bento-cli` as written in the docs 😄

2. More fundamentally, most projects I've seen that make use of linting tools (including flake8, black, isort, etc.) place them inside something like dev-requirements.txt, or otherwise make them dev-mode-installable. This makes it easy to set up the dev environment just by cloning the project, as opposed to being dependent on system state, or adding extra (potentially undocumented) steps to setting up the dev environment.

    Just to back up this claim, I did some quick searching, and not just many, but *most* of the projects I could think of off the top of my head actually seem to do this:
    * pydantic: https://github.com/samuelcolvin/pydantic/blob/master/tests/requirements.txt
    * starlette: https://github.com/encode/starlette/blob/master/requirements.txt
    * mypy: https://github.com/python/mypy/blob/a3d48cd57d3b31b320430c02356ef651e94ba144/test-requirements.txt
    * scikit-image: https://github.com/scikit-image/scikit-image/blob/ba4291a260565be43b655848a86155ac6cfa7c50/requirements/test.txt

    If I'm going to have bento be a part of my CI process, I'd ideally like it included as a development requirement in my pyproject.toml (or test-requirements.txt or whatever). But this means it would be installed in the local environment, in particular during testing, so I think it should play nice under those circumstances.

I could still imagine a bootstrapping approach where the core package can be installed without any dependencies, but the first thing it does when run is create the missing environments (the various other ones described in @arashd's list), with the dependencies it needs. Then, the core package installed in my project venv won't cause conflicts, but could still trigger jobs using the special environments in `~/.bento/`.

-----

The more I've thought of this, the more I'm a fan of having the main bento installation actually living in its own isolated environment (perhaps a third member of the `.bento/` dir). This would be dependent on solving the bootstrapping problem though.

The global approach @arashd is advocating would work fine for me for now though.

**Comment by arashd** [comment]
First of all, a huge thank you for all your wonderful feedback and attention to detail @dmontagu! Really appreciate it.

I absolutely agree that `npm/pip install --dev` is the way _every_ dev tool gets distribution and is made usable following a `git clone` and I'm a huge fan of putting bento into the dev dependencies of every project we're in, so installing bento isn't contingent on having heard about it. In fact, this raises a more interesting question for us: given that bento will be targeting non-python projects, as well, what's a good installation story, for say, a JS-only/Ruby+JS project? Language specifc tools can piggy back off of their language's package manager (EsLint and `npm i --dev`), but if we're exclusively on pypi, how can we get our tool on the user's machine?

For python, what you're advocating for sounds like a nice middle ground. Curious to hear what @nbrahms and @deifactor think about the above.

**Comment by dmontagu** [comment]
Homebrew might be a good option for mac; I'm not sure if there's a good analogy on linux that would be worth the maintenance burden (given how much more fragmented the package manager landscape seems to be there).

There's also the curl-to-bash (or similar) approach:
```
curl -sSL https://github.com/returntocorp/bento/raw/master/bin/bento-installer | bash
```
For better or worse this seems to be the approach a *lot* of things recommend for system-wide install these days, including at least homebrew, pyenv, and poetry.

You could provide instructions for a "more secure" global install for people who really care, but it seems like the majority of developers nowadays will happily copy and run a line like that these days, especially if it's got github as the host. 🤷‍♂️

To be clear, I personally would be fine using the curl line as the way to install 😅.

**Comment by arashd** [comment]
Great points. What worries me still is what you brought up in your second reason above:

> This makes it easy to set up the dev environment just by cloning the project, as opposed to being dependent on system state, or adding extra (potentially undocumented) steps to setting up the dev environment.

I worry that using Homebrew or curl + bash will only work if installation instructions are added to the project docs and all collaborators on the project read them. It doesn't automatically insert itself into the workflow of all collaborators the way ESLint and PyLint do as dev dependencies. 

I'm also imagining a scenario where Bento has been added to CI, but isn't running locally because collaborators don't know about it. As a developer, I'd opt for separate linters to avoid the inconsistency between errors in CI and locally. 

Thinking out loud here: What's the best way to distribute language-agnostic tooling in a world where most dev tooling is distributed through package managers?

**Comment by dmontagu** [comment]
> Language specifc tools can piggy back off of their language's package manager (EsLint and npm i --dev), but if we're exclusively on pypi, how can we get our tool on the user's machine?

The suggestion of homebrew was assuming no package manager was present (if not using PyPI). But if you could count on npm (or similar) to be present in that case, would that be the natural altervative? It seems like for your current use cases there will be *some* package manager present.

I guess you'd still need to ensure python was present in a suitable version on the system. Presumably that could be handled via homebrew or similar without too much difficulty; I could imagine it being scary to bootstrap a system python installation via npm 😅.

Maybe it would be reasonable to just make an npm package that looks for bento as a command line command (possibly with some more sophisticated python environment introspection), and if not found, just prints a warning with installation instructions?

-----

Also, just to clarify, I'd be fine with pip/npm distribution as the standard installation approach. The original point of this issue (related to global environments) was just that it would just be nice to support a "shared" install for power users that are going to use bento with every package they work on to prevent wasted disk space.

**Comment by dlukeomalley** [comment]
From a user today:

> also it created it's own virtualenvs? hmm i feel like I didn't really sign up for that

**Comment by dlukeomalley** [comment]
From a different user:

> - do not load a bunch of python libraries into `.bento` folder within the project, since it makes the project heavier (longer Docker build time), and corrupts PyCharm's search across the project files (because you start seeing a lot of search hits from libraries, not from your own project, which is not desirable).

**Comment by deifactor** [comment]
I think no matter what we do we're *always* going to have some users that like our approach, and some that don't. So I think user research has questionable value here. (I think this particular user's problems can be fixed just by using Dockerignore and .gitignore or similar.)

**Comment by dlukeomalley** [comment]
I'd like to close this issue in favor of #206.

Thank you all for the conversation on this topic these past few weeks! For 0.8 we're discussing moving Bento's .venv location to sidestep issues with editors and other tools picking up our dependency code (see #206). During that work there is an opportunity for us to optimize how .venv's are used across projects that use Bento, mainly we can re-use environments.

To @dmontagu's questions about installing Bento as a dev dep, we are supportive! See #93 for some light additional details.
