### ISSUE TITLE
Add progress bar to `bento archive`

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#8]
I ran Bento on Django, and Bento reported `⚠ 1252 findings in 35.12 s`. I then ran `bento archive` and Bento rewrote the whitelist with those findings, but it took a few moments, and during that time I was not shown a progress bar (meanwhile my laptop’s fans woke up and started spinning loudly).

**Comment by nbrahms** [comment]
This should be fixed in 0.1.0r4

**Comment by dlukeomalley** [comment]
Archive bars indeed exist. Closing out.
