### ISSUE TITLE
`bento check` takes 8 secs on 3300 LOC project

### ISSUE THREAD

**Issue by aryx** [returntocorp/bento#80]
**Describe the bug**
bento checks takes a long time, even after it reported issues.
(it arguably also takes a long time to check, 2seconds on a project of 3300 LOC (bento).

**Expected result**
Not taking more time than the time to check.
My guess is the telemetry is taking a long time. I have not a great internet
connection, =~ 9Mb/s  and sometimes git pull on github is also taking a long time (10secs),
but maybe a timeout on the telemetry could be useful for people with slow connections.

**Actual result**
When possible, provide verbose output (--verbose)

**Additional context**
screenshot:

<pre><font color="#8AE234"><b>pad@yrax</b></font>:<font color="#729FCF"><b>~/r2c/repos/bento-core</b></font>$ time bento check &gt; /tmp/xxx
Running Bento checks...
<font color="#3465A4">  r2c.bandit: |███████████████| 00:02, 🍱</font>
<font color="#3465A4">  r2c.flake8: |███████████████| 00:01, 🍱</font>
                                                 
<font color="#C4A000">⚠ 2 findings in 2.22 s</font>                           

To suppress all findings run `<font color="#3465A4">bento archive</font>`.

real	0m7.738s
user	0m5.619s
sys	0m0.538s
<font color="#8AE234"><b>pad@yrax</b></font>:<font color="#729FCF"><b>~/r2c/repos/bento-core</b></font>$ bento --version
bento/0.2.0b1
<font color="#8AE234"><b>pad@yrax</b></font>:<font color="#729FCF"><b>~/r2c/repos/bento-core</b></font>$ 
</pre>

**Comment by dlukeomalley** [comment]
Thanks for filing @aryx. This looks like a related symptom to #31; posting to the telemetry endpoint is blocking Bento from exiting.

CC @ulziibay

**Comment by dlukeomalley** [comment]
@aryx Can you upgrade and report back if you're still experiencing this issue? We have a fix in for you as of `bento/0.1.0.post1`, which is now available.

**Comment by aryx** [comment]
Still slow, but faster.

<pre>tests/integration/simple/foo.py
  0:0  <font color="#CC0000">error  </font> syntax error while parsing AST from file                    r2c.bandit     error

<font color="#C4A000">⚠ 10 findings in 2.01 s</font>

To suppress all findings run `<font color="#3465A4">bento archive</font>`.

real	0m3.662s
user	0m6.055s
sys	0m0.409s
<font color="#8AE234"><b>pad@yrax</b></font>:<font color="#729FCF"><b>~/r2c/repos/bento-core</b></font>$ bento --version
bento/0.2.0b1
<font color="#8AE234"><b>pad@yrax</b></font>:<font color="#729FCF"><b>~/r2c/repos/bento-core</b></font>$ 
</pre>

**Comment by aryx** [comment]
not sure why bento says it takes 2.01s when time bento check takes 6s.
