### ISSUE TITLE
hyperlinked check-id leads to 404 page

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#83]
**Describe the bug**
Clicking on a hyperlinked check-id leads to 404 page. This may be a widespread issue, but it was specifically found for flake8 E722: https://lintlyci.github.io/Flake8Rules/rules/E722.html

**Expected result**
Expected to be taken to documentation.

**Actual result**
![image](https://user-images.githubusercontent.com/605906/66602154-5c546a00-eb5e-11e9-9e9f-e0f6761367f2.png)

**Comment by arashd** [comment]
closing out given https://github.com/returntocorp/bento-core/commit/cd210ba58de453763855cc0d833c4bff13cffd15
