### ISSUE TITLE
remove eslint rule for defined but not used

### ISSUE THREAD

**Issue by daghan** [returntocorp/bento#88]
**Is your feature request related to a problem? Please describe.**
Just relaying feedback from Drew

**Describe the solution you'd like**
Don't kill the messenger

**Comment by dlukeomalley** [comment]
@DrewDennison Do you have more context you can add to this request or a motivating example?

**Comment by dlukeomalley** [comment]
Because we haven't heard any feedback in 21 days, I'm going to close out this issue for now. @DrewDennison @daghan Do you have any more context to offer?
