### ISSUE TITLE
`bento check` progress bars reset and freeze on large projects

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#9]
I ran Bento on Django, archived the initial 1252 findings, and then ran Bento again. 

During the subsequent Bento check run, the progress bars started to fill, then paused and the time counters stopped counting up:
<img width="477" alt="Screen Shot 2019-09-30 at 4 13 22 PM" src="https://user-images.githubusercontent.com/302941/65923355-7becd500-e39d-11e9-856d-840eae5ca045.png">

Then, when Bento finished the progress bars disappeared, though the timers “finished” their counts:
<img width="467" alt="Screen Shot 2019-09-30 at 4 13 36 PM" src="https://user-images.githubusercontent.com/302941/65923377-94f58600-e39d-11e9-8609-d1ccf570a576.png">

I would expect the progress bars to fill to 100% once Bento finishes those components (ESLint and Flake8 in this case).

**Comment by nbrahms** [comment]
Unfortunately this is the current behavior of the progress library we're using.

I'm filing this as a feature enhancement.

**Comment by nbrahms** [comment]
@pabloest Can you confirm that this is still an issue? 0.1.0r2 upgraded our progress bars in a way that should prevent freezes.

**Comment by dlukeomalley** [comment]
Appears to be resolved. Thanks!
