### ISSUE TITLE
# Question: Should I be installing bento into my virtual environments?

### ISSUE THREAD

**Issue by dmontagu** [returntocorp/bento#93]
Potentially related to #79, it's not clear from the docs whether it is intended / necessary to pip install bento-cli into each virtual environment for each project I'm working on.

-----

**If I *need* to install it into the virtual environment:**
Since bento is tightly pinning its dependencies (or at least `attrs`, which I also use 😄), running `pip install bento-cli` in a virtual environment can cause versions to change, which led to some surprises for me.

If bento *needs* to be installed into the same virtual environment as the project, it would be nice if the environment-modifying behavior could be addressed. Here are a couple possible approaches, though you all would probably have your own opinions:

1. Remove explicit dependencies on commonly used external packages (like `attrs`). If they are fundamentally necessary, maybe bootstrap if not detected at runtime (e.g., installing them into `.bento/` and updating the python path when bento runs?).

2. Loosen the version pinning, and handle version inconsistencies a little more gracefully in application logic.

3. Maintain bento-specific forks of the dependencies that are just renamed to prevent pip install conflicts (but are otherwise unmodified).

**In general, it feels to me like pinning dependencies on commonly used libraries is likely to cause pain if bento needs to be installed in the same environment as the project. Even if it doesn't need to be, if that is how most people install it when following the docs, I think the problem still exists.**

-----

**If I *don't need* to install it into the virtual environment:**
Maybe the install guide could be updated to explain how to install it "globally", or preferably via some approach that results in bento having an isolated environment. (This would be fine even if it is just a linked note with an "advanced usage" warning or similar, to keep things streamlined for new users).

This would probably solve #79.

**Comment by nbrahms** [comment]
Hi @dmontagu . Thanks for the question, which I think raises completely valid points.

Our intention is to not be opinionated about how Bento is installed. We recognize that users have a large assortment of varied Python environments, and we'd like to play nice with as many as possible.

To that end, you should be free to include Bento in your global, user, or project install (for the latter, we'd recommend it as a dev dependency only).

Your point about pinned dependencies is well taken. I'll open an issue to expand our compatibility ranges.

**Comment by nbrahms** [comment]
One last point worth noting:

One can always install `bento` in its very own virtual environment as a fallback. We aim to minimize the necessity of this method, but it should work reliably.

**Comment by dlukeomalley** [comment]
Given usage over the past few weeks I'd like to close this issue. Folks are installing both globally and within a project, depending on their own preferences and dev process. We're happy to support both and don't have an opinion for the time being! :)
