### ISSUE TITLE
Check results not printed if I don't scroll thru all results

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#94]
**Describe the bug**
When I run `bento check` and get a large number of results, pressing `q` to exit less doesn't print check summary, unless I scroll all the way to the bottom.

**Expected result**
That I see the summary even if I haven't scrolled down to look at every single results (this is tedious when there are hundreds)

**Actual result**
Nothing is printed except the progress bars.

**Additional context**
version: bento/0.1.0.post1, 
MacOS
Project: Vue.Draggable

Below are two example runs, first without scrolling all the way, second with scrolling.

```bash
$ bento check
Running Bento checks...
  r2c.eslint: |███████████████| 00:11, 🍱

$ bento check
Running Bento checks...
  r2c.eslint: |███████████████| 00:12, 🍱

⚠ 5092 findings in 12.40 s

To suppress all findings run `bento archive`.
```

**Comment by nbrahms** [comment]
Hi @arashd 

This was an issue with the tool that was fixed in 0.1.0, so I was surprised to see it crop back up here.

I tried to reproduce using the project and version you've quoted above, but was not able to.

Can you post the output of `bento --version` you used to generate this output? I'm suspicious that you may be using an outdated version of the tool.

Thanks!

**Comment by arashd** [comment]
```bash
$ bento --version
bento/0.1.0.post1
$ bento check
Running Bento checks...
  r2c.eslint: |███████████████| 00:12, 🍱
$
```

**Comment by arashd** [comment]
Nathan was unable to reproduce this even after installing Fish, which we thought was the only weirdness in my environment. @dlukeomalley can I ask that you confirm you can't reproduce this? We can close out and attribute to other env weirdness on my machine if that's the case.

**Comment by arashd** [comment]
Let's close this out for now since I'm the only person seeing it, and reopen if it crops up again.
