### ISSUE TITLE
Tool takes many tens of seconds to archive findings in minified es files

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#95]
**Describe the bug**
There's no progress indicator/spinner when a large number of items are being read/persisted to/from archive. Tool progress bars have finished/haven't appeared, and user doesn't know they're waiting for something.

For the rest of the life of the project, this happens every time archive is run.

**Expected result**
That there's at least a simple `persisting/reading results to/from archive...` message

**Actual result**
No indication that something is happening for at least 15 seconds, so I think the process is in an infinite loop. 

```bash
bento archive
  r2c.eslint: |███████████████| 00:11, 🍱

```
^ progress bar is done, timer has stopped but nothing happens for a while

**Comment by nbrahms** [comment]
@arashd Can you add steps to reproduce? I'd like to look into this more.

Thanks!

**Comment by arashd** [comment]
I'm running `bento/0.1.1b3`. I run `bento archive` on [Vue.Draggable](https://github.com/SortableJS/Vue.Draggable), then run `bento check`.

The wait is after linting is done in `bento archive`, and before linting begins in subsequent invocations of `bento check`.

**Comment by dlukeomalley** [comment]
As of 0.3.0 we're default ignoring minified files (it's unclear that they should be analyzed by Bento). Let's close this issue out for now as fixed, and revisit if our current approach doesn't satisfactorily address the problem.
