### ISSUE TITLE
Add ability to run Bento on a single file (to support running "on-save" in vscode)

### ISSUE THREAD

**Issue by daghan** [returntocorp/bento#97]
**Is your feature request related to a problem? Please describe.**
I love running prettier every time I save a file. I'd like to be  able to do the same  for Bento.  VS Code has  ready-made hooks for that.

**Describe the solution you'd like**
Allow a  --file (or something similar) flag to run Bento against a single  file.

**Comment by dlukeomalley** [comment]
Thanks for filing @daghan. Marking this issue as being related to #47 and leaving some notes:

1. we'd need to support passing in file paths to `bento check`, which I suspect we're close to supporting given `bento check --staged-only` (CC @brendongo @deifactor)
2. we should document how to add Bento on-save to vscode, showing the settings snippet. See [Run On Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave)

**Comment by dmontagu** [comment]
Note the "run on save" functionality also exists in JetBrains IDEs using "File Watchers" (this is a plugin, but it is made by JetBrains and is bundled with PyCharm). I'm currently using this to get PyCharm to auto-run black and isort when I save my files.

Given the amount of computation done by flake8 I don't know whether I would want bento running on every save by default -- my computer gets hot enough as it is while running PyCharm (and a commit hook is probably enough), BUT if you do want to add documentation for this and don't already know how to set up a file watcher in a JetBrains IDE let me know and I can write a little blurb (that you can modify as you see fit).

**Comment by dmontagu** [comment]
Also, I'm assuming this is well beyond the scope of priorities for now, but something possibly worth thinking about -- running as a daemon. [Mypy has implemented this](https://mypy.readthedocs.io/en/latest/mypy_daemon.html) and the extreme performance improvements make it feasible for real-time display of info in the IDE.

I could imagine a similarly large gain in performance if flake8 and/or bandit have a programmatic (rather than command line) API and you could keep a daemon server running (that would at least eliminate all of the interpreter-starting overhead).

**Comment by dlukeomalley** [comment]
> Note the "run on save" functionality also exists in JetBrains IDEs using "File Watchers" (this is a plugin, but it is made by JetBrains and is bundled with PyCharm). I'm currently using this to get PyCharm to auto-run black and isort when I save my files.
> 
> I don't know whether I would want bento running on every save by default -- it would depend on how much computation gets performed, and my computer gets hot enough as it is while running PyCharm (and a commit hook is probably enough), BUT if you do want to add documentation for this and don't already know how to set up a file watcher in a JetBrains IDE let me know and I can write a little blurb (that you can modify as you see fit).

@dmontagu It would be much appreciated if it's quick for you, we can do the same for VSCode and update the README.md in the next few days.

**Comment by dmontagu** [comment]
Here's a guide to file watchers for JetBrains IDEs (demonstrated with PyCharm):

--------

1. Open preferences, and make sure you have the File Watchers plugin installed and enabled. I think it is packaged with PyCharm, but some JetBrains IDEs do require you to install it manually. (It is an official JetBrains plugin though.)

![1-plugins](https://user-images.githubusercontent.com/35119617/67532843-a66c3e00-f67c-11e9-949e-a57664d58657.png)

-----

2. Go to the file watchers section under **Tools**. It will probably be empty if you've never added a watcher before. Click the **+** icon to create a new watcher, and select `<custom>` as the template type.
![2-file-watchers](https://user-images.githubusercontent.com/35119617/67532897-ecc19d00-f67c-11e9-8fb5-8891811ea636.png)

-----

3. This should have opened the **Edit Watcher** dialogue (you can reopen this by double clicking the watcher's row in the parent dialogue if you close this). You'll probably want to expand the **Working Directory and Environment Variables** section.

![3-edit-watcher](https://user-images.githubusercontent.com/35119617/67533062-85f0b380-f67d-11e9-9fd5-dbf270087bc0.png)

-----

4. Next, you'll want to edit various settings to configure the watcher as desired:

![4-edit-watcher-2](https://user-images.githubusercontent.com/35119617/67533087-9e60ce00-f67d-11e9-96cc-bc653131b6ad.png)

Some of the more important settings:
* **File type:** You'll want to set the file type to whatever type of file you want bento to lint (presumably just Python, but maybe JS too? That might need to be done as a second watcher; I've never done that before.)
* **Scope:** should probably just be `Project Files`, in case you open any non-project files (e.g., scratches) and don't want to auto-run bento on them
* **Program:** the command line command to run the program (`bento`, in your case)
* **Arguments:** the arguments to pass to the command. If there is a way to call bento on an individual file, you would set that up here. Note the use of the `$...$` for macros -- more on that in a bit
* **Working directory:** I'm not sure if this matters for bento, but if it does, you can set it here. It may be important if bento reads config files based on the directory from which it is called.
* **Auto-save edited files to trigger the watcher** You probably don't want this on
* **Trigger the watcher regardless of syntax errors** You probably don't want this on
* **Show console:** I think by default the console only appears if there are errors; I'm not sure what logic you'd want for bento, but it might make sense to make it "error" depending on whether there is something you want to show in the IDE? Maybe it already does that?

------

5. There are a large number of macros available for configuring how the watcher is called. I think the options I included above are probably the right ones for use with bento, but if not, there is a nice scrollable list if you click the "Insert Macro..." button that gives you a preview of how it would be expanded for the file you have selected:

![5-macros](https://user-images.githubusercontent.com/35119617/67533425-bb49d100-f67e-11e9-93fd-84cf60bf0185.png)

------


Feel free to copy as much of the text that I've provided above as you want, but I would just request that you capture new screenshots if you want to include them in your own documentation.

**Comment by dlukeomalley** [comment]
I'll incorporate this tomorrow, thank you very much @dmontagu! 🙏

**Comment by dlukeomalley** [comment]
Closing in favor of #134 that specifically tracks the documentation portion of this issue. Thanks all!
