### ISSUE TITLE
Node-based tools should use yarn if configured on project

### ISSUE THREAD

**Issue by nbrahms** [returntocorp/bento#98]
**Is your feature request related to a problem? Please describe.**
Currently, node-based tools are installed using `npm`. However, `npm` and `yarn` don't play nicely with each other, and one or the other should be used on a project.

**Describe the solution you'd like**
If `yarn` is in use on a project, install tools using `yarn`, not `npm`.

**Comment by nbrahms** [comment]
Fixed in 0.1.1b3

**Comment by arashd** [comment]
confirmed fix in `bento/0.1.1b6`
