### ISSUE TITLE
r2c.flake8 E117 is arguably stylistic and should not be enabled

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#99]
Make sure you are running the latest version of Bento.

**Describe the bug**
r2c.flake8 E117 is arguably stylistic and should not be enabled
error description is: "over-indented (comment)"

**Additional context**
`bento/0.1.0r6`

**Comment by dlukeomalley** [comment]
@minusworld and I discussed this last week and I think he had some changes in flight to remove E117. iirc it wasn't a documented flake8 check and so we missed excluding it in the first pass.

**Comment by minusworld** [comment]
I think I disabled E117 already 🤔 

https://github.com/returntocorp/bento-core/pull/66/files

**Comment by dlukeomalley** [comment]
Confirmed this is fixed in our latest release when running `bento init`
